### ISSUE TITLE
directory structure violates PhET convention

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#1]
Source-code directory structure for a 1-screen sim should look like this:

```js
js/
 curve-fitting/
    model/
    view/
```

**Comment by pixelzoom** [comment]
@jbphet said on Skype:
> Let me look at it on Monday.  I think I know what happened.  I set up the repo, then didn't run simula-rasa until they had committed a couple of things, so we probably collided a bit.  I'll clean it up.

**Comment by jbphet** [comment]
Looks like @andrey-zelenkov has fixed this.  Related commits are:
b6cc312a0c0b1e318ba2a69708b38e0fed8df987
086810752d40e0f1f12b6b67f4fe8910c9d76ef6

Closing.
