### ISSUE TITLE
User should be able to get a point by clicking anywhere on the bucket

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#10]
Just as we did with Least-Squares Regression (https://github.com/phetsims/least-squares-regression/issues/35), a user should be able to drag a point by clicking anywhere on the bucket.

**Comment by andrey-zelenkov** [comment]
Added getting point by clicking anywhere on the bucket. Reassign to @amanda-phet for verification.

**Comment by amanda-phet** [comment]
I was not able to get a point from clicking on the bucket. I still need to click directly on an orange point.

**Comment by amanda-phet** [comment]
This seems to be working now. Closing.
