### ISSUE TITLE
recommendations for improving Curve model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#101]
I was pulled off of curve-fitting before I could address this. But @ariel-phet asked me to jot down some of my thoughts.

Model type `Curve` is the heart of the model, and it's a bit of a mess.

It has these Properties for the polynomial coefficients and constant (all of which I will refer to herein as coefficients):

``` js
    PropertySet.call( this, {
      a: 0, // coefficient for x^3 term
      b: 0, // coefficient for x^2 term
      c: 0, // coefficient for x^1 term
      d: 0, // polynomial constant term
      ...
```

The implementation is very rigid/brittle in how it requires these specific Properties, and only supports a 3rd order polynomial.  And it tries to reuse 1 instance of a Curve for all orders. 

A few suggestions to improve this:
1. Instead of separate Properties for each coefficient, have an array of coefficients whose length corresponds to the order of the polynomial that describes the curve.
2. If you must have separate Properties for each coefficient, don't name them 'a', 'b', etc. How to label them is a choice made by the view, not the model.  And as discussed in https://github.com/phetsims/curve-fitting/issues/83, there are other ways that the polynomial formulas might be expressed in the view.
3. Curve is unnecessarily complex because 1 instance is used for all orders of polynomials, and the irrelevant (higher order) terms have their coefficients set to zero.  A better implementation would use instance 1 instance of Curve for each order needed, and switch between them.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/curve-fitting/issues/87

**Comment by SaurabhTotey** [comment]
It seems like right now, the curve model is completely different from what is described here. At least for myself, I do not find the Curve model too hard to understand. As such, I am marking this issue as ready for review.
