### ISSUE TITLE
Curve is manipulated when data point is outside curve boundary

### ISSUE THREAD

**Issue by bryo5363** [phetsims/curve-fitting#11]
I noticed that when the user selects a data point from the collection while a curve is displayed on the graph, the curve will automatically adjust to fit that point. I think that the curve. should change only when the new data point is inside of the graph.

![curvefitting](https://cloud.githubusercontent.com/assets/7717368/7685960/9b87cf0c-fd4f-11e4-92eb-1c2c9ad318ba.gif)

**Comment by amanda-phet** [comment]
I agree- that is an odd behavior right now.

**Comment by amanda-phet** [comment]
@ariel-phet Let's discuss this one.

**Comment by amanda-phet** [comment]
This appears to be fixed in the latest version. Closing.
