### ISSUE TITLE
font for math symbols and variables

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#110]
Noted while working on https://github.com/phetsims/scenery-phet/issues/348 ...

Curve Fitting is not using `MathSymbolFont`(Times New Roman, italic) for math symbols and variables, which is inconsistent with other PhET sims.

Assigning to @amanda-phet (lead design in credits) to decide if this needs to be addressed.

**Comment by pixelzoom** [comment]
I discussed with @amanda-phet. This sim should definitely use the math font.  

See GRAPHING_QUADRATICS/GQSymbols for a pattern that could be used here.  The font is handled via HTML markup, then passed to RichText.

**Comment by SaurabhTotey** [comment]
In 607397d0c9941cbb6a6a4d4b33d79c4ff695a602, I switched to the math font for the chi and r symbols in the DeviationsAccordionBox.

**Comment by SaurabhTotey** [comment]
I believe that by this point, all the symbols and variables in the equations in curve-fitting use MathSymbolsFont.

**Comment by SaurabhTotey** [comment]
Assigning to @amanda-phet to review. All symbols now use MathSymbolsFont, but it doesn't look to great in terms of kerning in regards to the chi squared values or the r squared values in the DeviationsAccordionBox. @chrisklus suggested the use of FormulaNode instead.

**Comment by amanda-phet** [comment]
The formula in the dialog looks good. 

Is it possible for chi squared and r squared to *not* use an italic '2' in the exponent?

**Comment by SaurabhTotey** [comment]
Sure! I switched the exponents in the DeviationsAccordionBox to use a normal font without italics. Now, only the symbols are using MathSymbolFont. However, it seems to me like the kerning issue is still there where part of the `X` runs into the 2 exponent. Below is what it looks like in master.

<img width="168" alt="equations" src="https://user-images.githubusercontent.com/22577113/59624606-69070b00-90f4-11e9-8584-f42315eeaa9e.png">

**Comment by pixelzoom** [comment]
I was going to suggest using [letter-spacing](https://www.w3schools.com/cssref/pr_text_letter-spacing.asp) to adjust the kerning.  But it's not supported by RichText (see RichText `FONT_STYLE_MAP` for a list of supported CSS keys.)   I suggest either living with it, or creating an issue to add `letter-spacing` support to RichText.  No idea how difficult the latter is.

Related issue... To my eye, a little horizontal space between the "=" and the value field would make this look less squished.

**Comment by amanda-phet** [comment]
It's not a huge deal to me if you leave the spacing as it is. I agree with @pixelzoom about the equal sign. A little more space to both the left and right would be nice.

**Comment by SaurabhTotey** [comment]
I added a space before and after the equals sign so it now looks like this.

<img width="182" alt="Deviations Accordion Box Equations" src="https://user-images.githubusercontent.com/22577113/59633644-36680d00-910a-11e9-8261-7475502598d9.png">

**Comment by amanda-phet** [comment]
Looks great to me.
