### ISSUE TITLE
use InfoButton

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#111]
Curve Fitting info button should use SCENERY_PHET/buttons/InfoButton, which uses the international "info" symbol.  Should definitely _not_ be using a '?', even though it's translatable

**Comment by pixelzoom** [comment]
![curve-fitting](https://user-images.githubusercontent.com/3046552/38587069-66156c46-3cdd-11e8-9ee9-ccdb40ef2878.jpg)

**Comment by SaurabhTotey** [comment]
I have made helpButton an InfoButton rather than a TextPushButton. This has made the button a circle rather than a square.

**Comment by SaurabhTotey** [comment]
In my latest commit, I just horizontally centered the info button as is shown in the design in #119.
