### ISSUE TITLE
Convert from TWEEN to Twixt

### ISSUE THREAD

**Issue by samreid** [phetsims/curve-fitting#112]
As discussed in https://github.com/phetsims/joist/issues/387#issuecomment-419600722, it would be nice to use Twixt instead of TWEEN.  This sim has 1 occurrence of `new TWEEN.Tween(...)`.  Assigning to the responsible dev.  After completing this issue, check if the hold on https://github.com/phetsims/joist/issues/387 can be removed (if this was the last "Convert from TWEEN to Twixt" issue).

**Comment by SaurabhTotey** [comment]
As of right now, I have changed the Point animations to use Twixt. However, a lot of the code regarding animations in that file can be simplified. I will mark this issue as ready to review once I simplify the logic in Point so that it is simpler and easier to read.

**Comment by SaurabhTotey** [comment]
Point has now been slightly cleaned up. As such, I believe this issue has been completed, and I am marking this as ready for review.
