### ISSUE TITLE
cosmetic issues with equation 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#115]
The equation that appears in the upper-left corner of the graph has a lot of cosmetic problems. Besides not using the proper font for symbols (see https://github.com/phetsims/curve-fitting/issues/110):

- the equation is not using plus and minus operators, it's using the signs of values
- operators should be black, values should be blue
- should the sign of 'b' be shown when its value is positive? e.g. +0.119

![screenshot_825](https://user-images.githubusercontent.com/3046552/48009421-ef785a80-e0d8-11e8-969f-ddca2a6222ed.png)

Compare to the _Standard Form_ screen of Graphing Quadratics:

![screenshot_826](https://user-images.githubusercontent.com/3046552/48009429-f2734b00-e0d8-11e8-89a8-78f1b205585b.png)

Assigning to @amanda-phet to decide what should change.

**Comment by pixelzoom** [comment]
Also noted that when move sliders, there is no proximity with the changing values. May want to revisit the overall design.

**Comment by amanda-phet** [comment]
At this point, given how far along this sim is, I'd like to leave the overall design as it is (even if it's somewhat dated compared to our newest sims). 

However, the text should definitely be updated. Here is a mockup illustrating how the equation should look, as well as the panel with the equation, sliders, and labels. 
![image](https://user-images.githubusercontent.com/7852916/57102027-bca5cc80-6cdf-11e9-9421-843fa9fe186d.png)


Notice that the math font is being used here, which is times italic. This applies to variables only. Numerals (such as exponents or coefficients) should be sans-serif.

**Comment by pixelzoom** [comment]
Re equations...

The font for symbols is `SCENERY_PHET/MathSymbolFont`, which is `family: '"Times New Roman", Times, serif';` with `style: 'italic'`

Equations should use symbols and operators that are in `SCENERY_PHET/MathSymbols`. 

Superscripts (e.g. _x_<sup>3</sup>) should be done using HTML markup with `SCENERY/RichText`.

**Comment by SaurabhTotey** [comment]
I believe I have improved the appearance of the equation in the graph area so that it seems more similar to the graphing quadratics equation. However, spacing might still be an issue.

**Comment by SaurabhTotey** [comment]
Assigning to @amanda-phet to review current appearance of equation.

**Comment by amanda-phet** [comment]
The equation on the graph looks great! Although, I think the signs used to be blue to correspond better with the values in the sliders, especially if a value is negative. Is that an easy change to make? If not I can live with it as it is.

**Comment by SaurabhTotey** [comment]
The switch wasn't difficult at all! The coefficients' signs are now colored blue just like the coefficients themselves.

**Comment by amanda-phet** [comment]
Looks good. Thank you!
