### ISSUE TITLE
odd location for tick labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#116]
Tick labels in this sim are very strange - the labels are not at the end of the tick lines, they are on the opposite side of the axis.

![screenshot_829](https://user-images.githubusercontent.com/3046552/48011734-b2fb2d80-e0dd-11e8-8cc7-76634773d7f7.png)

Tick labels are typically at the ends of the tick lines, like this example from pH Scale:

![screenshot_828](https://user-images.githubusercontent.com/3046552/48010282-809c0100-e0da-11e8-8f8c-07ae030045cc.png)

Assigning to @amanda-phet to determine whether this should change.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/curve-fitting/issues/93, but not a duplicate.

**Comment by amanda-phet** [comment]
What do you think about just extending the tick marks? I prefer them on the left side, but I think this looks better than the original. 

![image](https://user-images.githubusercontent.com/7852916/48013002-8e548500-e0e0-11e8-8576-d998c36cfd41.png)

**Comment by pixelzoom** [comment]
@amanda-phet See [1.0.0-dev.7](https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-dev.7/phet/curve-fitting_en_phet.html) and screenshot below for what I had in mind. I was easier to change the code than to make a mockup, and the code is now in a better place to accept change requests.  Does this look acceptable to you? 

![screenshot_831](https://user-images.githubusercontent.com/3046552/48016372-a92af780-e0e8-11e8-9501-fdd090219099.png)

**Comment by amanda-phet** [comment]
That looks good to me, thanks!

**Comment by pixelzoom** [comment]
👍
