### ISSUE TITLE
non-standard forms of linear and quadratic equations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#118]
Here's the form of equations used by this sim. 

Linear: y = cx + d
Quadratic: y = bx<sup>2</sup> + cx + d
Cubic: y = ax<sup>3</sup> + bx<sup>2</sup> + cx + d 

The symbols that this sim uses in linear and quadratic forms don't match standards, or what PhET has done in other sims. The standards are:

Linear: y = mx + b
Quadratic: y = ax<sup>2</sup> + bx + c

The current implementation looks suspiciously like a programming convenience.  Is there a pedagogical reason for this difference? Will it be a problem for students?

**Comment by amanda-phet** [comment]
There is a pedagogical reason for this- we want the variables to stay the same as you add/remove terms from the polynomial.

**Comment by pixelzoom** [comment]
Looks like I asked about this before and got the same answer, see https://github.com/phetsims/curve-fitting/issues/83.   Sorry about that.   Closing.
