### ISSUE TITLE
Deviations accordion box changes 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#119]
There are multiple open issues relating to the Deviations panel. While tweaking it to address these, I have made some other changes 

* #116 Tick label locations
* #111 New info button
* #110 Use math font (in this case, Chi and r should be math fonts) 
* Use persistent accordion box title 
* When the accordion box is minimized, keep the width the same 

![image](https://user-images.githubusercontent.com/7852916/48013355-5ac62a80-e0e1-11e8-99e5-3dfe9e0c2fd8.png)

![image](https://user-images.githubusercontent.com/7852916/48013371-631e6580-e0e1-11e8-9e68-51a3de24a727.png)

@pixelzoom let me know if I forgot something, or if you have any other ideas for improving this box.

**Comment by pixelzoom** [comment]
We'll have @SaurabhTotey start on this after completing #117.

**Comment by pixelzoom** [comment]
> * Use persistent accordion box title
> * When the accordion box is minimized, keep the width the same

Looks like both of these are already working properly.

**Comment by pixelzoom** [comment]
Also related to this is #120.  Code related to the "barometers" is not in good shape, lots of duplication.

**Comment by amanda-phet** [comment]
>Looks like both of these are already working properly. 

You're right, I wasn't looking at master!

**Comment by SaurabhTotey** [comment]
In my latest commit, I changed the fonts for the chi and r symbols so they now use the MathSymbolsFont. I also centered the info button horizontally. I still need to rework the barometers to have appropriate tick placement.

**Comment by SaurabhTotey** [comment]
At this point, I have also fixed the barometers and their appearance to be more similar to the image. As such, I believe that everything in this issue has been addressed.

**Comment by SaurabhTotey** [comment]
Assigning to @amanda-phet to review and then sign off. For the help button, I used a color picker on the image which says the icon's fill color is `rgb( 44, 107, 159 )`. As such, that is the current color of the info button on master as well, but I am happy to change anything that is needed.

**Comment by amanda-phet** [comment]
The panel looks good to me, although in #116 I think I had already signed off on the look of the barometers. So this change wasn't necessary, but I'm ok with this too! 

The blue color probably came from somewhere but I can't remember. I'm sure this blue is fine. Thanks!
