### ISSUE TITLE
Point flyback to bucket

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#12]
This sim could make use of implementing the flyback animations that Least Squares Regression has when points return to the bucket. Currently, in 1.0.0-dev.4, when a point is dragged off the graph and released, the point just disappears and it's not clear as to the fate of the point.
LSR sim:
http://phet.colorado.edu/sims/html/least-squares-regression/latest/least-squares-regression_en.html

**Comment by amanda-phet** [comment]
@phet-steele That is an interesting thought. Since this sim does not have an erase button and the flyback would only happen when a point is released, I am inclined to see how students interpret this behavior in interviews.
