### ISSUE TITLE
clean up bucketnode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#121]
Determine whether BucketNode can be replaced with SCENERY_PHET/BucketFront and SCENERY_PHET/BucketHole.

**Comment by pixelzoom** [comment]
@SaurabhTotey this is another relatively easy issue that you can start with.

**Comment by SaurabhTotey** [comment]
It seems like BucketNode uses BucketFront and BucketHole from SCENERY_PHET, but also adds extra functionality like to the bucket like a drag handler. From what I can tell, it seems like it would be difficult to replace BucketNode without re-implementing its functionality where it is used.
