### ISSUE TITLE
Some pixel polishes

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/curve-fitting#124]
@SaurabhTotey @amanda-phet Curve fitting is look close to where we might want to consider some polishes.

@SaurabhTotey one that should definitely be done is that the radio buttons are quite large visually currently. If you look at any recent published sim with radio buttons we tend to make the radius of the button approximately the same size as the first letter of the label.

We probably want to review some spacing and such as well, but lets definitely adjust the radio button size.

**Comment by amanda-phet** [comment]
I'm fine with the radio button size changing. 

One polish that comes to mind is that the equation in the adjustable fit panel jumps a little when it is linear because there is no exponent to offset it like the other equations. If we could keep those all aligned in some way that might be nice.

**Comment by SaurabhTotey** [comment]
Equations now have a constant vertical size, so they will no longer jump up and down when switching between linear and other forms.

As for the radio button sizes, I have decreased the round radio buttons to have a radius of 6 and the square buttons to have a width of 14. This is what it looks like now in master.
<img width="201" alt="Buttons" src="https://user-images.githubusercontent.com/22577113/59872424-ef228c00-9356-11e9-8daf-66416cd29a9d.png">

**Comment by ariel-phet** [comment]
@amanda-phet can you plan to bring this to the next design meeting @kathy-phet is at, might be good to have her eyes on the sim before we publish and see if she has any desired polishes

**Comment by amanda-phet** [comment]
Will do. Let's plan on 7/11/19.

**Comment by SaurabhTotey** [comment]
Closing this issue because other issues have been opened from the design meeting.
