### ISSUE TITLE
Layer equation accordion box on top with some transparency

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#126]
We would like the equation accordion box to be layered on top of the points, error lines, error bars, and labels. It should have a white fill with at least 0.8 opacity (might need to play with values to get it right so that it is easy to read when any labels are behind it).

**Comment by SaurabhTotey** [comment]
I have moved the equation to the front and given it an opacity of 0.8. Here's what it looks like in master on a busy graph. Objects below the equation are still draggable.
<img width="564" alt="graphequationinfront" src="https://user-images.githubusercontent.com/22577113/61144097-305b1700-a491-11e9-8282-16f6b2b27a9b.png">

**Comment by amanda-phet** [comment]
@kathy-phet what do you think? I think it looks good, but the thing that bothers me right now is that I can see the 10 label on the y-axis. So, this solution works well with points layered behind the equation, but I don't like constantly seeing that 10. Since we will be changing the bounds of the graphing area with #130 I will wait to make a final opinion.

**Comment by kathy-phet** [comment]
To fix that issue that Amanda notes, you can do what I said, basically make the expanded box have 2 fill layers - one that is behind the points but infront of the axis - that is solid white, and a second that is in front of the points that is a transparent white. 

A bit tricky for sure, but I believe we have done this sort of thing in other sims. @SaurabhTotey could ask on the dev channel about it.

**Comment by SaurabhTotey** [comment]
This should be an easy fix, but the code will look slightly weird. I'll assign this to myself and get to work on this solution.

**Comment by SaurabhTotey** [comment]
Now the equation is layered such that the accordion box is on top of everything, and there is also a background behind the accordion box that is behind everything except for the graph axes. Points are still grabbable from under the equation.

Below is what it looks like.
<img width="558" alt="graphempty" src="https://user-images.githubusercontent.com/22577113/61158977-c9048d80-a4b7-11e9-90d3-86bed43e6136.png">
<img width="558" alt="graphbusy" src="https://user-images.githubusercontent.com/22577113/61158982-cb66e780-a4b7-11e9-8b6d-2d52ce97af4c.png">

**Comment by SaurabhTotey** [comment]
I'll experiment further with this once I tackle #130.

**Comment by SaurabhTotey** [comment]
Assigning to @amanda-phet to review and see whether the opaque layer of the equation in front of the axes but behind the points is still needed (which is what is on master right now). If not, I can revert back to having the equation only have the semi-transparent layer that will show everything below it including the axes.

**Comment by kathy-phet** [comment]
I think it looks good with the layering.

**Comment by amanda-phet** [comment]
I think this is working nicely.
