### ISSUE TITLE
touch areas review

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#129]
- [ ] make the points and error bars "touch to snag" 
- [ ] decrease the height of the error bar touch areas slightly 
- [ ] increase the height of the point touch area slightly

**Comment by SaurabhTotey** [comment]
I have adjusted the pointer touch areas, and after some testing, it looks like the points and the error bars already have touch-to-snag. Below is what the pointerAreas look like.
<img width="558" alt="pointerareas" src="https://user-images.githubusercontent.com/22577113/61309227-09f9ec00-a7af-11e9-9cfa-cb326cabd7b8.png">

**Comment by amanda-phet** [comment]
Those look great to me!
