### ISSUE TITLE
Adjustable fit values not saved

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#13]
1. Put some points on the graph.
2. Select either a quadratic or cubic curve.
3. Choose adjustable fit and move all the sliders around. Take note of their values.
4. Switch back to best fit.
5. Go back to adjustable fit. Your values for c and d (and b for cubic curves) will have been lost and set to match the values of the best fit. Values for b (or a for cubic curves) remain unaffected.

Tested in Win 8.1 
Troubleshooting information:
Name: Curve Fitting
URL: http://www.colorado.edu/physics/phet/dev/html/curve-fitting/1.0.0-dev.4/curve-fitting_en.html?dev
Version: 1.0.0-dev.4 2015-05-18 16:31:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# curve-fitting 1.0.0-dev.4 Mon May 18 2015 10:31:50 GMT-0600 (Mountain Daylight Time)","curve-fitting":{"sha":"e701e0eb5ee5f5dfbbe194fcc31bbd52e354a238","branch":"master"},"assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"1199217e4b4a158afe5cf2fd59e5a7a087fd4179","branch":"master"},"babel":{"sha":"3ef6bce9237080ffa2d92c30d28b2d6f966bddc4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"8fd8eb6a428c4ea10ce8511af0f2cce6bfc61612","branch":"master"},"dot":{"sha":"9e70b8cac3ddfcb9e1dff786b23bc64de3b98350","branch":"master"},"joist":{"sha":"c9f2b67459f59f292a59bca7a714cd6f0908b4f9","branch":"master"},"kite":{"sha":"affd230ecc0d01f4f217ed7060007e3c71de4937","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"a69dfeb8452edb51348eb2187ce25939a8b0dda1","branch":"master"},"scenery-phet":{"sha":"4ca937ebfe35a021d4c781a4c6877be22ddbcf9b","branch":"master"},"sherpa":{"sha":"7c1f8f58b67a29014fb75ef4c80c3a5904193630","branch":"master"},"sun":{"sha":"5ae6c12634dc188f5b9ba8bc3aca76dcf96448c8","branch":"master"},"vegas":{"sha":"5d1f054ececac34752bbd2edcf940a6fdfdcb017","branch":"master"},"vibe":{"sha":"bad425472494babb88c260adbd718230d567ec3a","branch":"master"}}

**Comment by phet-steele** [comment]
Causes me to have situations with two graphs that look different but have the same equation:

![best curve](https://cloud.githubusercontent.com/assets/5863899/7686823/e03b0c12-fd55-11e4-858e-d3503875055d.PNG)

![adjustable curve](https://cloud.githubusercontent.com/assets/5863899/7686826/e5233f9c-fd55-11e4-8bfe-02dabcf37c46.PNG)

Also notice this second curve became cubic.

**Comment by amanda-phet** [comment]
The fact that you have a cubic is very problematic.

**Comment by amanda-phet** [comment]
I think this issue should be addressed by simply making sure the Adjustable fit values are remembered when switching between Best fit and Adjustable fit.

The issue of the curve types will be addressed with #15.

**Comment by amanda-phet** [comment]
@phet-steele Can you confirm if this is still happening or not?

**Comment by phet-steele** [comment]
Yes this still happens.

**Comment by amanda-phet** [comment]
Thanks. @MDmitrieva can you please address this issue? 

The adjustable fit values should be "remembered" when you switch between adjustable fit and best fit.

**Comment by andrey-zelenkov** [comment]
Fixed via https://github.com/phetsims/curve-fitting/commit/aa7bcc613c53a10153fcfddd6b0beaf859a1353b commit. Reassign to @phet-steele for verification.

**Comment by phet-steele** [comment]
:+1:
