### ISSUE TITLE
label axes

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#130]
we should label the axes with *x* and *y*.

**Comment by amanda-phet** [comment]
this means we should probably change the graph range to -10 to 10, similar to Graphing Lines. The axes arrow would extend beyond the white box with labels to the right of each arrow head.

**Comment by amanda-phet** [comment]
copy tick marks that are currently in Graphing Lines... one mark for every unit with major marks at 5 and 10.

**Comment by SaurabhTotey** [comment]
I have changed the graph a bunch so it now looks like this.
<img width="560" alt="Graph" src="https://user-images.githubusercontent.com/22577113/61410210-1b232580-a8a1-11e9-9739-7d6b95b641c5.png">

This is almost exactly the same as graphing-lines, but one key difference is that there are no grid lines. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
This is working for me. It's quite busy with all of the tick marks, but that's ok. Thanks for making these changes!
