### ISSUE TITLE
Clicking the information button freezes the sim

### ISSUE THREAD

**Issue by jaspearias** [phetsims/curve-fitting#132]
<b>Test Device</b>

Chadwick

  <b>Operating System</b>

Chrome OS

  <b>Browser</b>

  Chrome

  <b>Problem Description</b>

For https://github.com/phetsims/QA/issues/394 
When testing the query parameter for rtl clicking on the information button freezes the whole screen. If you refresh the page it goes back to normal and you are able to click on all of the other buttons, but if the information button is clicked again the whole screen freezes. It only happens in the query parameter for rtl. 

  <b>Steps to Reproduce</b>

1. Click on the simulation
2. Type in query parameter "?stringTest=rtl" at the end of URL
3. Play around with the sim (without clicking the information button)
4. Click on the information button (screen freezes) 
5. Refresh the page and everything is back to normal

  <b>Visuals</b>

https://drive.google.com/file/d/18WkNQuH2cBNzWMEVcB9aoI6zVt2EYNIi/view?usp=sharing

**Comment by SaurabhTotey** [comment]
The error in the console is
```Error: KaTeX parse error: Unexpected character: 'ت' at position 0: ̲تست (زبان)_r^2```

As such, I believe this issue more is an issue with using unicode characters than using RTL. I'll look into this further.

**Comment by SaurabhTotey** [comment]
I'll remove the translatability for the equation right now due to https://github.com/phetsims/scenery/issues/457#issuecomment-156634759. However, I won't work more on this issue until a more decisive decision has been reached about what to be done about this.

**Comment by SaurabhTotey** [comment]
I am marking this issue as status:blocked until https://github.com/phetsims/scenery/issues/457 has an answer because this issue is reliant on the resolution to that issue.

**Comment by amanda-phet** [comment]
Decision 8/15/19: defer the ability to translate the equation until after a 1.0 release. @SaurabhTotey will continue to look into KaTex and if the newer version allows for unicode characters.

**Comment by SaurabhTotey** [comment]
Closing because it has since been solved since updating KaTeX to a newer version.
