### ISSUE TITLE
Items look interactable even while dragging a separate item

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#133]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/394
Not certain if this is a bug.  If not, feel free to close.  When dragging an object, if you pass over another object it clearly indicates it can be interacted with, even though you are currently dragging another object.
**Steps to reproduce**
1. Take out at least two points and put them near each other on the graph
2. Start changing one of the error bars by clicking and dragging it
3. Make sure your mouse passes over one of the other error bars while doing step 2

**Visuals**
![hightlightwhiledraggingalready](https://user-images.githubusercontent.com/41024075/62581180-96a34180-b865-11e9-9ba6-1feaa2795d28.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Curve Fitting‬
URL: https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-dev.15/phet/curve-fitting_all_phet.html
Version: 1.0.0-dev.15 2019-08-06 21:04:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by SaurabhTotey** [comment]
To complicate things a little, the other items (points and error bars and such) are still draggable as long as the device has multi-touch and the objects are dragged with a different finger.

I'll defer the decision of what should be done about this to @amanda-phet.

**Comment by amanda-phet** [comment]
@ariel-phet thoughts about this? This doesn't seem all that unusual to me, but if it looks buggy should we fix it? 

@KatieWoe is this unique to this sim? I have never tried looking at this in another sim, but I'm curious if it happens elsewhere.

**Comment by KatieWoe** [comment]
@amanda-phet I looked at Graphing Lines and it does seem to happen in other sims.  It just seems more likely to occur/be noticed here.

**Comment by amanda-phet** [comment]
Thanks. I'll keep an eye out for this in interviews tomorrow!

**Comment by ariel-phet** [comment]
@amanda-phet it does strike me as a bit odd. You have "pointer down" while dragging these items, and it seems there should be a way to say if you have pointer down (with the mouse) you don't get hover behavior on other items.

@SaurabhTotey you might want to ask the dev channel if there is a workaround for this sort of thing already. Having the multitouch behavior is fine, but when you are interacting with one object (pointer down/mouse click held) it seems odd to get "hover" behavior on other objects.

**Comment by SaurabhTotey** [comment]
I believe I have addressed this on master now, but I will need to make sure on a multitouch device.

**Comment by amanda-phet** [comment]
The students I interviewed didn't notice a problem relating to this issue, but I'm glad @SaurabhTotey was able to look into a fix.

**Comment by SaurabhTotey** [comment]
After briefly testing on a multitouch device, it seems like this issue can be closed. Please reopen if I missed anything, or there needs to be more done.
