### ISSUE TITLE
Should the values option show residual value?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#134]
For https://github.com/phetsims/QA/issues/394.
I noticed that when the residuals and values checkboxes are both checked, the value shown is still that of the greyed out error bars, but no indication of what the residual bar's value is.
![shouldresidualvaluesshow](https://user-images.githubusercontent.com/41024075/62582846-0ec03600-b86b-11e9-86df-bd9d98152093.png)

**Comment by SaurabhTotey** [comment]
On an extremely brief skim through the design doc, I couldn't find anything regarding this. I'll leave the decision up to @amanda-phet as to what should be done about this.

**Comment by amanda-phet** [comment]
No, that's not necessary. That feature is more about showing visually what the residual is.
