### ISSUE TITLE
Difficult pointer areas around error bars

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#135]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/394
I noticed that the pointer areas for the error bars can, by default overlap a bit with their point.  The visible part of the bars can even overlap with the point's pointer area entirely.  The first aspect can make grabbing the bars with a touchscreen difficult, and the later aspect can make it difficult in either case.  Even though the bar's pointer areas extend to the side, there isn't a clear visual clue for this unless you use the query parameter.
My two possible suggestions:
1. Layer the bar's pointer areas over the point's.  That way they can be moved out of the way to access the point if a full overlap happens.
2. Extend the visual part of the bar to match the pointer areas, to give cue that they can be grabbed.

**Visuals**
![extendup](https://user-images.githubusercontent.com/41024075/62643890-34e6e400-b906-11e9-9adf-f150065a37a6.png)
![pointareas](https://user-images.githubusercontent.com/41024075/62643896-37493e00-b906-11e9-9617-282cbb714ac8.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Curve Fitting‬
URL: https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-dev.15/phet/curve-fitting_all_phet.html?showPointerAreas
Version: 1.0.0-dev.15 2019-08-06 21:04:15 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by SaurabhTotey** [comment]
I haven't pushed these changes to master, but below is what it looks like when I change the width from 20 to 26. I can still further expand or reduce these. Assigning to @amanda-phet to review and decide on what is best.

<img width="1440" alt="withoutpointerareas" src="https://user-images.githubusercontent.com/22577113/62656639-e34c5280-b921-11e9-8772-8b1ee2997dc6.png">
<img width="1440" alt="withpointerareas" src="https://user-images.githubusercontent.com/22577113/62656640-e5161600-b921-11e9-9d8a-7fc26050ee7d.png">


They still don't quite expand outside of the range of the point's touch area, so I can further widen deltas if that is what should be done.

**Comment by SaurabhTotey** [comment]
When I increased the size of the error bars, I forgot to decrease the dilation so that it wouldn't grow with the rectangle. I have done that now, so below is what it looks like right now on master.

I can further increase or decrease the size of the error bars and their touch dilations as necessary.

![WithPointerAreas](https://user-images.githubusercontent.com/22577113/62800211-17e61880-baa0-11e9-9350-c43cf8462208.png)
![WithoutPointerAreas](https://user-images.githubusercontent.com/22577113/62800214-187eaf00-baa0-11e9-80c1-b9bd3adb66ff.png)

**Comment by amanda-phet** [comment]
I liked the original size of the error bars, and I think the touch areas were working out ok. 

@KatieWoe did you have trouble grabbing anything? or did you more just want the bars to appear bigger and grabbable? 

I am interviewing this sim on touch tomorrow (8/13/19) and would like to keep the bars as they are and see how it goes before making this change. @SaurabhTotey you can revert your change or keep it, either way I can just use the dev version for the interview.

**Comment by KatieWoe** [comment]
I had a bit of trouble in the case when the the error bars have been shrunk beyond their default size

**Comment by SaurabhTotey** [comment]
I will revert my change for right now.

**Comment by amanda-phet** [comment]
The pointer areas posed no issues at all for both interviews done on touch.
