### ISSUE TITLE
Should the X2 bar show that it extends further?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#136]
For https://github.com/phetsims/QA/issues/394
I noticed that X2 could get to be much larger than 100, and though the scale has an arrow to show this, the bar does not indicate that is going off the the scale.  Should it somehow?
![shouldthisindicate](https://user-images.githubusercontent.com/41024075/62656955-8dc47580-b922-11e9-850d-5a896562b2fc.png)

**Comment by SaurabhTotey** [comment]
I'll defer this design decision to @amanda-phet.

**Comment by amanda-phet** [comment]
That's a good question. I thought at one time the red bar went past 100 in that case, but I could be wrong. In either case, it doesn't really matter all that much. The point is, X^2 is really really big. 

@SaurabhTotey if it's easy to make the red bar go past 100 when it's over 100, please do so. up to the base of the arrowhead seems fine to me.

**Comment by SaurabhTotey** [comment]
I have implemented that change in master.
<img width="242" alt="x2barometerfill" src="https://user-images.githubusercontent.com/22577113/62894060-2e42dd00-bd09-11e9-8927-d33a8a691679.png">

Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
I think that looks reasonable. 

Can you include this change in a new dev version for me to use tomorrow?

**Comment by SaurabhTotey** [comment]
Sure! This change is included in the dev.17 version at https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-dev.17/phet/curve-fitting_en_phet.html.

**Comment by amanda-phet** [comment]
This looked good in interviews and students were focused on what made the meter increase/decrease, which is the goal. I think this change made sense so I'll close the issue.
