### ISSUE TITLE
Lines outside of graph can look odd

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#137]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/394
The line created to fit the curve (either automatically or by the user) extends beyond the bounds of the graph, but does not extend indefinitely.  This can be useful, but it also looks rather strange if part of a curve is cut off in the manner.  I think it would look much less strange if it cut off at the edge of the graph.  Should this be reevaluated?

**Visuals**
![looksodd](https://user-images.githubusercontent.com/41024075/62658567-52c44100-b926-11e9-8f70-ca2e7f098fde.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: X
URL: https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-dev.15/phet/curve-fitting_all_phet.html?stringTest=X
Version: 1.0.0-dev.15 2019-08-06 21:04:15 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by SaurabhTotey** [comment]
I'll defer this design decision to @amanda-phet.

**Comment by SaurabhTotey** [comment]
Just for a little more context, the line in Graphing Lines extends past the graph, but the curves are cut off at the graph in Least Squares Regression and Graphing Quadratics.

**Comment by amanda-phet** [comment]
Has this always been the case? Or did this change when you changed the graph to match Graphing Lines? 

Ideally the curves are contained only within the white square of the graph. @SaurabhTotey can you make that happen?

**Comment by SaurabhTotey** [comment]
This change happened when I tried to make this graph look like the graph from Graphing Lines. I can make the curve stay only inside the bounds of the white part of the graph pretty easily.

**Comment by SaurabhTotey** [comment]
Ok, I have changed this on master. Below is what it looks like.
<img width="1440" alt="Screen Shot 2019-08-08 at 3 54 10 PM" src="https://user-images.githubusercontent.com/22577113/62740341-d0ef1900-b9f4-11e9-9a44-2d95309f998c.png">

**Comment by amanda-phet** [comment]
Looks great! Thanks!
