### ISSUE TITLE
Sim won't open in IE

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#138]
For https://github.com/phetsims/QA/issues/394
The sim will not load in Internet Explorer
```SCRIPT438: Object doesn't support property or method 'includes'```

**Comment by SaurabhTotey** [comment]
I believe I have replaced the code that was causing this issue, but I'll check once I make another dev-version.

**Comment by SaurabhTotey** [comment]
After now building dev version 16, it seems like this simulation now works on IE. I've only tested on one device, so please reopen this issue if it actually isn't solved.
