### ISSUE TITLE
Equation, but no line

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#139]
I noticed this in interviews and it seems very odd to me. 

To reproduce: 
1. Place one point in the grid
2. Turn on curve

There is a linear equation shown (which updates as the point moves), but there is no line being graphed (which is not consistent with the equation- an equation of a line). 

I see three possible options as fixes: 
(1) The equation should read y = 0x + 0, which is technically still a line, but would be hidden behind the x-axis. 
(2) Graph the line reflected in the equation
(3) Don't show an equation at all until there are 2+ points, but I'm not sure what we would put in that accordion box.

**Comment by amanda-phet** [comment]
Decision: 
Instead of an equation
![image](https://user-images.githubusercontent.com/7852916/63121698-4f523a80-bf62-11e9-8baa-e63d92cd6f4e.png)

the accordion box will simply read "undefined"

**Comment by SaurabhTotey** [comment]
This has now been implemented in master. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Looks good to me.
