### ISSUE TITLE
review and sign-off for model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#144]
Related to code review https://github.com/phetsims/curve-fitting/issues/143.

In https://github.com/phetsims/curve-fitting/issues/71, I see a discussion between 2 developers about completing [model.md](https://github.com/phetsims/curve-fitting/blob/master/doc/model.md) and implementation-notes.md.   But I can find no paper trial indicating that the lead design (@amanda-phet) reviewed and signed off on model.md.  It's typically reviewed by the lead design because the audience for model.md is non-developers, including teachers.  This is also typically done before code review, since model.md is one of the first things read by the code reviewer.

See for example https://github.com/phetsims/gas-properties/issues/79, the review and sign-off of model.md for gas-properties.

**Comment by amanda-phet** [comment]
I forgot to reference this image, but I just deleted one sentence from model.md that was not accurate. The rest looks fine to me.
