### ISSUE TITLE
reconsider overall layout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#145]
Related to code review #143.  

Why is the bucket so far away from the graph?  Why is there so much empty space below and right of the graph?  Here's what the sim looks like now, very lopsided:

<img width="915" alt="screenshot_1403" src="https://user-images.githubusercontent.com/3046552/63893078-7703c280-c9a6-11e9-966e-791b61139de1.png">

Something like this looks better and makes the bucket more usable:

![screenshot_1403](https://user-images.githubusercontent.com/3046552/63893171-af0b0580-c9a6-11e9-9b0b-3bd6da8dc2a5.jpg)

**Comment by pixelzoom** [comment]
This looks even more balanced to me, combined with the change suggested in #146:
* Graph is in the center of the screen
* Deviations accordion box is horizontally centered in negative space to left of graph, vertically centered on the graph.
* Right side control panels are horizontally centered in negative space to right of graph, top-aligned with the graph.
* Bucket is below left-aligned with panels, bottom aligned with graph.

![ss7](https://user-images.githubusercontent.com/3046552/63893894-8a179200-c9a8-11e9-8484-b1981cf9b358.jpg)

**Comment by pixelzoom** [comment]
Oops.  And then I found "Adjustable fit" sliders, see below.  So maybe we can at least move the bucket closer to the graph, and horizontally center panels in negative space?

<img width="917" alt="screenshot_1404" src="https://user-images.githubusercontent.com/3046552/63894141-25106c00-c9a9-11e9-8ac5-08091f47c074.png">

**Comment by pixelzoom** [comment]
Before changing any layout code, decide what to do about #157 (non-standard layout), since that will change everything.

**Comment by ariel-phet** [comment]
@pixelzoom I think we would definitely be open to moving the bucket once the layout bounds are revised

**Comment by pixelzoom** [comment]
This is being handled over in #157.  Closing.
