### ISSUE TITLE
symbol for "delta"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#147]
Noticed while reviewing English strings for code review #143.

In curve-fitting-strings_en.json:

```js
  "deltaEqualsPattern": {
    "value": "D<sub>y</sub> = {{deltaValue}}"
  },
```

This appears on the points, like this:

<img width="127" alt="screenshot_1405" src="https://user-images.githubusercontent.com/3046552/63896225-b33b2100-c9ae-11e9-97e1-9f65cf8d31a2.png">

Is "D" the proper symbol to be using for "delta"?  Why not "Δ" or "δ" ?

**Comment by amanda-phet** [comment]
The original uses 'D' so I just assumed that's what Mike wanted, but I just emailed an confirmed with him that it should use the capital greek delta. Please use '∆' instead of 'D'.

**Comment by pixelzoom** [comment]
Changed in the above commit, see screenshot below.   In #159, we're still working out whether this should be using math font.

<img width="147" alt="screenshot_1423" src="https://user-images.githubusercontent.com/3046552/63968878-d7a20680-ca5d-11e9-9943-d594766359da.png">
