### ISSUE TITLE
return curveFitting.register

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#148]
Related to code review #143.

Throughout this sim's code, `register` is used like this:

```js
define( require => {
  ...

  class ReducedChiSquaredStatisticDialog extends Dialog {
    ...
  }

  curveFitting.register( 'ReducedChiSquaredStatisticDialog', ReducedChiSquaredStatisticDialog );

  return ReducedChiSquaredStatisticDialog;
} );
```

Since `register` returns its 2nd arg, the preferred PhET convention is:

```js
return curveFitting.register( 'ReducedChiSquaredStatisticDialog', ReducedChiSquaredStatisticDialog );
```

@SaurabhTotey up to you whether you want to change this.  It's not wrong the way it is. I mainly wanted you to be aware of the preferred pattern.

**Comment by SaurabhTotey** [comment]
I have made the change because it seems cleaner. Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
👍 closing
