### ISSUE TITLE
fitProperty should be an instance of EnumerationProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#149]
Related to #143 code review.

In CurveFittingModel, this should be an `EnumerationProperty`:

```js
      // @public {Property.<FitType>}, the method of fitting the curve to data points
      this.fitProperty = new Property( FitType.BEST, { validValues: FitType.VALUES } );
```

I.e.:

```js
      // @public the method of fitting the curve to data points
      this.fitProperty = new EnumerationProperty( FitType, FitType.BEST );
```

**Comment by SaurabhTotey** [comment]
Sounds good, I'll get on that. Perhaps the documentation here https://github.com/phetsims/phet-core/blob/master/js/Enumeration.js#L40-L44 should be updated as well then.

**Comment by SaurabhTotey** [comment]
I have made the change for CurveFittingModel. Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
👍 Commit looks good.

I don't think the documentation for Enumeration should say anything about EnumerationProperty, for the same reason that Vector2 shouldn't say anything about Vector2Property.  Those classes are values, and their API and doc shouldn't know anything about Property.
