### ISSUE TITLE
use Property validation options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#150]
Related to this item in code review #143:

> - [ ] Are Property value validation options (`valueType`, `validValues`, etc...) utilized? Is their presence or lack thereof properly documented?

There are currently no usages of validation options in this sim.   This info is important for catching programming errors, and for future PhET-iO instrumentation.

For example, in Curve.js:

```js
      // @public {Property.<number>} r^2 deviation value, a number ranging from 0 to 1
      this.rSquaredProperty = new NumberProperty( 0 );
```

should be:

```js
      // @public {Property.<number>} r^2 deviation value
      this.rSquaredProperty = new NumberProperty( 0, {
        range: new Range( 0, 1 )
      }  );
```

In Point.js:

```js
      this.isInsideGraphProperty = new DerivedProperty(
        [ this.positionProperty ],
        position => CurveFittingConstants.GRAPH_BACKGROUND_MODEL_BOUNDS.containsPoint( position )
      );
```

should be:

```js
      this.isInsideGraphProperty = new DerivedProperty(
        [ this.positionProperty ],
        position => CurveFittingConstants.GRAPH_BACKGROUND_MODEL_BOUNDS.containsPoint( position ), {
      valueType: 'boolean'
     } );
```

So....

* Take a look at all NumberProperty instances, add `range` for any that have a range.
* Take a look at all DerivedProperty instances, add `valueType` or `isValidValue` where possible.

**Comment by pixelzoom** [comment]
Using validation options will also make assertions like this in CurveFittingModel unnecessary:

```js
      // validate Property values and update curve fit
      this.orderProperty.link( order => {

        // ensure the order is 1, 2 or 3: linear, quadratic or cubic
        assert && assert( order === 1 || order === 2 || order === 3, `invalid order: ${order}` );
...
```

**Comment by SaurabhTotey** [comment]
I have now added more property validation. Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
Looks good, closing.
