### ISSUE TITLE
move createRadioButton out of CurveOrderPanel constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#152]
Related to code review #143.

In CurveOrderPanel constructor:

```js
      /**
       * Creates a uniform radio button for this panel.
       *
       * @param {number} value
       * @param {string} label
       * @returns {AquaRadioButton}
       */
      const createRadioButton = ( value, label ) => new AquaRadioButton(
        orderProperty,
        value,
        new Text( label, CurveFittingConstants.CONTROL_TEXT_OPTIONS ),
        CurveFittingConstants.RADIO_BUTTON_OPTIONS
      );
```

It would be better to add `@param {Property} property` to this function and move it outside of the constructor.  I.e.:

```js
      /**
       * Creates a uniform radio button for this panel.
       *
       * @param {Property} property
       * @param {number} value
       * @param {string} label
       * @returns {AquaRadioButton}
       */
      function createRadioButton( property, value, label ) {
        return new AquaRadioButton(
          property,
          value,
          new Text( label, CurveFittingConstants.CONTROL_TEXT_OPTIONS ),
          CurveFittingConstants.RADIO_BUTTON_OPTIONS
      }
```

Then usage becomes:

```js
      // radio buttons
      const linearButton = createRadioButton( orderProperty, 1, linearString );
      const quadraticButton = createRadioButton( orderProperty, 2, quadraticString );
      const cubicButton = createRadioButton( orderProperty, 3, cubicString );
```

There's probably only one instance of CurveOrderPanel in the sim.  But you want to get in the habit of moving function definitions outside of the constructor when possible.  If they're inside the constructor, you get an instance of that function for every instance of your class. Outside the constructor you have one function instance shared by all instances of the class.   This will keep your memory footprint down a bit.

**Comment by SaurabhTotey** [comment]
I moved the function out of the class. Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
Looks good.  But I changed the order of args to `createRadioButton` to match the order of args to `AquaRadioButton`, i.e.:

`function createRadioButton( orderProperty, value, label )`

`new AquaRadioButton( orderProperty, value, new Text( label, ... ), ... )`

And since `orderProperty` is the thing that's the same in all of the call, it's nice to have it first in the calls:

```js
      const linearButton = createRadioButton( orderProperty, 1, linearString );
      const quadraticButton = createRadioButton( orderProperty, 2, quadraticString );
      const cubicButton = createRadioButton( orderProperty, 3, cubicString );
```

If that looks OK to you, feel freer to close.

**Comment by SaurabhTotey** [comment]
Oh I completely missed that! That does look better though, so I'll close this. Thanks!
