### ISSUE TITLE
use nested options for CoefficientSliderNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#153]
Related to code review #143.

CoefficientSliderNode is a good opportunity to use nested options. The first part of its constructor looks like this:

```js
    /**
     * @param {Property.<number>} property parameter to track.
     * @param {Range} range - Possible range for property.
     * @param {string} label - Label for slider.
     * @param {Object} [options] for slider node.
     */
    constructor( property, range, label, options ) {
      options = _.extend( {
        trackFill: 'black',
        trackSize: new Dimension2( 120, 1 ),
        thumbSize: new Dimension2( 10, 20 ),
        minorTickLineWidth: 2,
        minorTickLength: 12,
        thumbTouchAreaYDilation: 4, // supposed to make touch horizontal areas flush; is YDilation since we rotate by 90; see #72
        thumbMouseAreaYDilation: 4,
        thumbMouseAreaXDilation: 10,
        labelOptions: {
          font: new PhetFont( {
            weight: 'bold',
            size: 13
          } ),
          fill: CurveFittingConstants.BLUE_COLOR,
          maxWidth: 20
        }
      }, options );
```

The doc "@param {Object} [options] for slider node" is incorrect, because `labelOptions` is not for Slider.

Something like this would be better. Note the use of `merge` and `sliderOptions`.

```js
    /**
     * @param {Property.<number>} property parameter to track.
     * @param {Range} range - Possible range for property.
     * @param {string} label - Label for slider.
     * @param {Object} [options] for slider node.
     */
    constructor( property, range, label, options ) {
      options = merge( {
        sliderOptions: {
          trackFill: 'black',
          trackSize: new Dimension2( 120, 1 ),
          thumbSize: new Dimension2( 10, 20 ),
          minorTickLineWidth: 2,
          minorTickLength: 12,
          thumbTouchAreaYDilation: 4, // supposed to make touch horizontal areas flush; is YDilation since we rotate by 90; see #72
          thumbMouseAreaYDilation: 4,
          thumbMouseAreaXDilation: 10
        },
        labelOptions: {
          font: new PhetFont( {
            weight: 'bold',
            size: 13
          } ),
          fill: CurveFittingConstants.BLUE_COLOR,
          maxWidth: 20
        }
      }, options );
```

**Comment by SaurabhTotey** [comment]
I switched to the more consistent nesting and use of merge. Assigning to @pixelzoom to review.

**Comment by pixelzoom** [comment]
The label font got reverted in https://github.com/phetsims/curve-fitting/commit/dee6c345a2a35ba6eb785a529ad698acc19aa50b.  I had changed it to `CurveFittingConstants.COEFFICIENT_FONT` as part of #157, and you set it back to `font: new PhetFont( { weight: 'bold', size: 13 } )`.    So I've fixed that in the above commit.

**Comment by pixelzoom** [comment]
The label font got reverted in https://github.com/phetsims/curve-fitting/commit/dee6c345a2a35ba6eb785a529ad698acc19aa50b.  I had changed it to `CurveFittingConstants.COEFFICIENT_FONT` as part of #157, and you set it back to `font: new PhetFont( { weight: 'bold', size: 13 } )`.    So I've fixed that in the above commit.

**Comment by pixelzoom** [comment]
Sorry that that didn't notice before, but the `options` arg to `CoefficientSliderNode` is never used.  The single use of `CoefficientSliderNode` is in `FitPanel`:

```js
      const ascendingSliders = slidersAttributes.map(
        ( sliderAttribute, index ) => new CoefficientSliderNode(
          sliderPropertyArray[ index ],
          sliderAttribute.range,
          sliderAttribute.string,
          { enabledProperty: sliderAttribute.enabledProperty }
        )
      );
```

So in this case, there's no need to have any options related to the Slider or Text label. Simply pass the desired options to the Slider and the Text.  I've made that change in the above commit.  This also saves a tiny bit of memory, since the options literals are not created once, instead of for each instance of `CoefficientSliderNode`.  

Back to @SaurabhTotey to for review. Feel free to close if all looks well.

**Comment by pixelzoom** [comment]
Hmm... There's something else that's strange here, so I've restored `sliderOptions` and `labelOptions` in the above commits.

In FitPanel:

```js
      const ascendingSliders = slidersAttributes.map(
        ( sliderAttribute, index ) => new CoefficientSliderNode(
          sliderPropertyArray[ index ],
          sliderAttribute.range,
          sliderAttribute.string,
          { enabledProperty: sliderAttribute.enabledProperty }
        )
      );
```

Where is the `enabledProperty` option value being used?  CoefficientSliderNode and its subclass VBox have no such option.  And while using this sim, I haven't run into any situation where a slider is disabled.

**Comment by pixelzoom** [comment]
It looks to me like `enabledProperty` is unused and can be delete from `slidersAttributes` and the options to `new CoefficientSliderNode`.

**Comment by SaurabhTotey** [comment]
Looking in FitPanel on lines 138 and 139, I see this comment
```
// if the sliders are not disabled they will be able to change
// and behave as described in #15 and #37
```

I don't know if this still holds true, so I will need to test on a multitouch device before deleting `enabledProperty`.

**Comment by SaurabhTotey** [comment]
After doing some testing, it looks like the enabledProperty didn't do anything, so I removed it. Closing this issue now.
