### ISSUE TITLE
Differentiate between `Property` and "property" in comments

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#154]
For this code review item in #143:

> - [ ] Differentiate between `Property` and "property" in comments. They are different things. `Property` is a type in AXON; property is any value associated with a JavaScript object. Often "field" can be used in exchange for "property" which can help with clarity.

There are 9 uses of "property" in comments that should be "Property".

**Comment by SaurabhTotey** [comment]
I changed all the usages of "property" in the comments that I could find. However, I only counted 8. Could you point me to where the last one is @pixelzoom?

**Comment by pixelzoom** [comment]
Sorry, I must've counted wrong.  Looks like you got them all.  Closing.
