### ISSUE TITLE
use assert more liberally

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#155]
Use of `assert` is a little light in this sim.  I only see 6 occurrences of `assert && assert`.    No need to change anything at this point, but I wanted to make sure you understand when to use `assert`.   Use it to check pre and post assumptions for methods.  And in an untyped language like JavaScript, `assert` is one of your most important tools for doing your own type checking. 

For comparison, gas-properties has 494 occurrences of `assert && assert`.

**Comment by SaurabhTotey** [comment]
Ok, I'll be sure to make more use of assert for the future. Thanks for the heads up!
