### ISSUE TITLE
sim uses non-default layout bounds with different aspect ratio

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#157]
Noted in code review #143.

Default layoutBounds for a ScreenView (the red rectangle you see with `?dev`) are:

```js
var DEFAULT_LAYOUT_BOUNDS = new Bounds2( 0, 0, 1024, 618 );
```

This sim uses custom layout bounds, with a different aspect ratio.  In CurveFittingConstants:

```js
SCREEN_VIEW_OPTIONS: { layoutBounds: new Bounds2( 0, 0, 768, 504 ) },
```

This has been determined to cause problems in the past, and in https://github.com/phetsims/joist/issues/542#issuecomment-455300368 the census was:
> * going forward we'll use default layoutBounds for everything, regardless of porting cost

@ariel-phet @amanda-phet @arouinfar Since this is an unpublished sim, should this be addressed? or is it too late in the process?

**Comment by pixelzoom** [comment]
By the way... This is no fault of @SaurabhTotey or any of the other authors.  The custom bounds were present from the beginning, probably ported from a legacy version.   And the authors had no way to know about  phetsims/joist#542 .

**Comment by pixelzoom** [comment]
Considering that the general layout needs revisiting (see #145), switching to the default layoutBounds is probably something that should be done.

**Comment by ariel-phet** [comment]
@pixelzoom do you think it would be most efficient for you to make this switch?

**Comment by pixelzoom** [comment]
It depends on the release schedule for this sim, not sure if I have the time.  

Here's what the sim looks like currently, with custom `layoutBounds: new Bounds2( 0, 0, 768, 504 )`:

<img width="1105" alt="screenshot_1414" src="https://user-images.githubusercontent.com/3046552/63911927-42652a80-c9e9-11e9-9453-7cb442b94ca4.png">


Here's what the sim will look like with no adjustments and default `layoutBounds: new Bounds2( 0, 0, 1024, 618 )`.  The graph gets bigger, everything else gets smaller.

<img width="1106" alt="screenshot_1413" src="https://user-images.githubusercontent.com/3046552/63911898-2bbed380-c9e9-11e9-84a1-9ccf13e4acd1.png">

**Comment by pixelzoom** [comment]
Here's the result of 15 minutes.  Did not adjust font sizes or point sizes.  Graph fills more of the play area, less overall negative space.  Bucket could also be under Deviations accordion box.

I did not commit, patch attached below.  Let me know if you want me to continue.  If so, we should talk about #145 layout.

<details>
<summary>Patch</summary>

```
Index: js/curve-fitting/CurveFittingConstants.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/curve-fitting/CurveFittingConstants.js	(revision c22fc8b5a2c09ee331b6c8ccb8463dae04257dbb)
+++ js/curve-fitting/CurveFittingConstants.js	(date 1567055902272)
@@ -16,8 +16,6 @@
 
   const CurveFittingConstants = {
 
-    SCREEN_VIEW_OPTIONS: { layoutBounds: new Bounds2( 0, 0, 768, 504 ) },
-
     // speed for dataPoints to reach the bucket when animated
     ANIMATION_SPEED: 65, // in model units per second;
 
Index: js/curve-fitting/view/CurveFittingScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/curve-fitting/view/CurveFittingScreenView.js	(revision c22fc8b5a2c09ee331b6c8ccb8463dae04257dbb)
+++ js/curve-fitting/view/CurveFittingScreenView.js	(date 1567056421376)
@@ -37,7 +37,7 @@
      */
     constructor( model ) {
 
-      super( CurveFittingConstants.SCREEN_VIEW_OPTIONS );
+      super();
 
       // view-specific Properties
       // @public {Property.<boolean>} determines visibility of the "Deviations" accordion box (upper left hand side panel)
@@ -55,14 +55,26 @@
       // @public {Property.<boolean>} determines visibility of the curve fit
       const curveVisibleProperty = new BooleanProperty( false );
 
+      // create a model view transform, graph is centered and fills the ScreenView height
+      const modelViewTransform = ModelViewTransform2.createSinglePointScaleInvertedYMapping(
+        new Vector2( 0, 0 ),
+        new Vector2( this.layoutBounds.centerX, this.layoutBounds.centerY ),
+        25.5 //TODO compute this
+      );
+
+      // create the graph area node - responsible for the rendering of the axes, ticks and background.
+      const graphAreaNode = new GraphAreaNode( modelViewTransform );
+
       // deviations accordion box, at left of screen
       const deviationsAccordionBox = new DeviationsAccordionBox(
         deviationsAccordionBoxExpandedProperty,
         model.points,
         model.curve.chiSquaredProperty,
         model.curve.rSquaredProperty,
-        curveVisibleProperty,
-        { left: 10, top: 10 }
+        curveVisibleProperty, {
+          centerX: this.layoutBounds.left + ( graphAreaNode.left - this.layoutBounds.left ) / 2,
+          centerY: graphAreaNode.centerY
+        }
       );
 
       // all other controls, at right of screen
@@ -72,23 +84,10 @@
         model.fitProperty,
         curveVisibleProperty,
         residualsVisibleProperty,
-        valuesVisibleProperty,
-        { right: this.layoutBounds.right - 10, top: deviationsAccordionBox.top }
-      );
-
-      // create a model view transform
-      const graphAreaWidth = controlPanels.left - deviationsAccordionBox.right - GRAPH_PADDING_LEFT_RIGHT * 2;
-      const graphCenterX = 0.5 * ( controlPanels.left + deviationsAccordionBox.right );
-      const graphCenterY = graphAreaWidth / 2 + deviationsAccordionBox.top;
-      const scale = graphAreaWidth / CurveFittingConstants.GRAPH_NODE_MODEL_BOUNDS.width;
-      const modelViewTransform = ModelViewTransform2.createSinglePointScaleInvertedYMapping(
-        new Vector2( 0, 0 ),
-        new Vector2( graphCenterX, graphCenterY ),
-        scale
-      );
-
-      // create the graph area node - responsible for the rendering of the axes, ticks and background.
-      const graphAreaNode = new GraphAreaNode( modelViewTransform );
+        valuesVisibleProperty, {
+          centerX: this.layoutBounds.right - ( this.layoutBounds.right - graphAreaNode.right ) / 2,
+          top: modelViewTransform.modelToViewY( 10 )
+        } );
 
       // create the equation node (accordion box) in the upper left corner of the graph
       const equationBoxLeft = modelViewTransform.modelToViewX( -10 ) + 10;
Index: js/curve-fitting/view/BucketNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/curve-fitting/view/BucketNode.js	(revision c22fc8b5a2c09ee331b6c8ccb8463dae04257dbb)
+++ js/curve-fitting/view/BucketNode.js	(date 1567056672148)
@@ -31,8 +31,8 @@
   const BUCKET_COLOR = 'rgb( 65, 63, 117 )';
 
   // bucket position is to the left and up from the bottom left corner of graph, in model coordinates
-  const BUCKET_POSITION_X = CurveFittingConstants.GRAPH_NODE_MODEL_BOUNDS.minX - 3;
-  const BUCKET_POSITION_Y = CurveFittingConstants.GRAPH_NODE_MODEL_BOUNDS.minY;
+  const BUCKET_POSITION_X = CurveFittingConstants.GRAPH_NODE_MODEL_BOUNDS.maxX + 2;
+  const BUCKET_POSITION_Y = CurveFittingConstants.GRAPH_NODE_MODEL_BOUNDS.minY + 4;
 
   // position of points inside bucket
   const POINT_POSITIONS = [
```

</details>

<img width="920" alt="screenshot_1416" src="https://user-images.githubusercontent.com/3046552/63913042-0089b380-c9ec-11e9-95d6-847b703d45b9.png">

**Comment by pixelzoom** [comment]
Here's another layout, keeps the bucket away from the Reset All button.

<img width="916" alt="screenshot_1417" src="https://user-images.githubusercontent.com/3046552/63913415-4b57fb00-c9ed-11e9-83f6-c13b69796546.png">

**Comment by ariel-phet** [comment]
@pixelzoom the layout just above looks good to me

**Comment by pixelzoom** [comment]
Summary of changes in the above commit:
* switched to default layoutBounds
* increase font sizes
* increased spacings
* increased margins
* increases point radius
* moved specification of fonts/spacing/margins to CurveFittingConstants, to make tweaking easier
* made Reset All button the standard size

There are still a few things that need adjustment:
* GraphEquationAccordionBox and its contents
* X<sup>2</sub> and r<sup>2</sup> value displays
* Possibly make the "barometer" axes taller

**Comment by pixelzoom** [comment]
The Equations accordion box is problematic.   It should be using `ToggleBox`, which needs to be migrated from vector-addition to scenery-phet.

**Comment by pixelzoom** [comment]
This is at a good place for review.  @amanda-phet @ariel-phet have a look, let me know what you'd like tweaked.  @SaurabhTotey FYI, many changes here, let me know if you have questions.

**Comment by amanda-phet** [comment]
I like the new layout! I like the larger graph, and the location of the bucket. Can we possibly make the bucket smaller though? It looks enormous, but the pile of points is the same size.

**Comment by pixelzoom** [comment]
@amanda-phet The bucket size was reduced by @SaurabhTotey.  Please review and let us know if there's anything else to do here.   Feel free to close if all good.

**Comment by amanda-phet** [comment]
I see on phettest now- that bucket size looks more reasonable. All looks good to me.

**Comment by zepumph** [comment]
One more TODO pointing here, https://github.com/phetsims/curve-fitting/blob/2aececec22c03dc91c78c698df9e471dfe0f9b42/js/curve-fitting/view/CurveFittingScreenView.js#L61

From https://github.com/phetsims/chipper/issues/1372
