### ISSUE TITLE
unused dispose functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#158]
Related to this item for code review #143:
> - [ ] Do all types that require a `dispose` function have one? This should expose a public `dispose` function that calls `this.disposeMyType()`, where `disposeMyType` is a private function declared in the constructor.  `MyType` should exactly match the filename.

Implementing `dispose` functions that are not used is also a problem.  It's unexercised code, and it confuses future maintainers about what really needs to be disposed.  That said...

I see implementations of `dispose` for BarometerNode, BucketNode, EquationNode, PointNode.   But the only call to `dispose` that I see being used is for PointNode, in BucketNode:

```js
        const removalListener = removedPoint => {
          if ( removedPoint === addedPoint ) {
            this.removeChild( pointNode );
            pointNode.dispose();
            points.removeItemRemovedListener( removalListener );
          }
        };
```

If the `dispose` implementations for BarometerNode, BucketNode, and EquationNode are really not needed, then I recommend deleting them. 

I also recommend putting a note in implementation-notes.md about what needs to be disposed any why.

**Comment by SaurabhTotey** [comment]
I removed the dispose functions for BarometerNode and EquationNode, but I was unable to find BucketNode's dispose. Did I miss something, or is this all good now?

**Comment by pixelzoom** [comment]
Looks like you got them all @SaurabhTotey.  I must've been hallucinating about BucketNode, or might have been looking at `FRACTIONS_COMMON/BucketNode`.  

Closing.
