### ISSUE TITLE
symbols with incorrect font

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#159]
There are some symbols that are not rendered in the correct font.  In 1.0.0-dev.17:

- [x] _y_ in the Equations accordion box and Fit panel:

<img width="381" alt="screenshot_1420" src="https://user-images.githubusercontent.com/3046552/63963651-bdaef680-ca52-11e9-8deb-2f7b55c7faab.png">
<img width="202" alt="screenshot_1421" src="https://user-images.githubusercontent.com/3046552/63963653-bf78ba00-ca52-11e9-9919-2b8dfdc30559.png">

- [ ] _D<sub>y</sub>_ on points:

<img width="140" alt="screenshot_1422" src="https://user-images.githubusercontent.com/3046552/63963718-d91a0180-ca52-11e9-9e7f-b123479930fb.png">

**Comment by pixelzoom** [comment]
Fixing _y_ was straightforward.

Fixing _D<sub>y</sub>_ is not going to be straightforward.  The label and value are all one string.

@amanda-phet could you please confirm that _D<sub>y</sub>_ should be in Math font?

**Comment by pixelzoom** [comment]
In #147, 'D' was changed to '∆', so points now look like this:

<img width="147" alt="screenshot_1423" src="https://user-images.githubusercontent.com/3046552/63968783-acb7b280-ca5d-11e9-80b7-4bbd0e83475c.png">

@amanda-phet should '∆<sub>y</sub>' be in PhET's standard math font?

**Comment by amanda-phet** [comment]
Yes, they probably should use math font and should look like this:
![image](https://user-images.githubusercontent.com/7852916/64035928-2f4c7a80-cb0f-11e9-8dea-cbaaf34519e5.png)

The delta should not look italicized, and I'm pretty sure our "math font" is times italic, right? So if you make it "math font" I'd like to take one last look at it.

**Comment by amanda-phet** [comment]
Isn't delta unicode? Anyway, I'm not exactly sure how it's going to be handled, but I imagine if it's a symbol that it won't be affected by the font.

**Comment by pixelzoom** [comment]
It going to be difficult to use different font for 'Δ' and 'y'.  We typically do subscripts using RichText and HTML markup, in this case: "Δ<sub>y</sub>".   To do different fonts, we'll need to create custom code to handle the subscript.  And because font height different across browsers, the 'y' subscript will not be in the same place as other subscripts (may be off a pixel or so).

So my recommendation is to pick one of these options:

(1) Leave with 'y' in non-math font, as it is in the current implementation.  This is zero cost.

(2) Use math font for both the 'Δ' and 'y', i.e _Δ<sub>y</sub>_.  This is 30-60 minutes of code changes.

If it were my decisions, I'd go with (2).

**Comment by pixelzoom** [comment]
I said:
> ... So my recommendation is to pick one of these options: ...

Scratch that. I figured out how to style the  'Δ' and 'y' separately, see screenshot below. 

@amanda-phet please verify in master.

<img width="153" alt="screenshot_1426" src="https://user-images.githubusercontent.com/3046552/64067432-9f2d3480-cbe5-11e9-9b07-9379d14611ef.png">

**Comment by amanda-phet** [comment]
Looks good to me.
