### ISSUE TITLE
Performance Review

### ISSUE THREAD

**Issue by SaurabhTotey** [phetsims/curve-fitting#160]
This sim still needs to undergo performance review. I built [dev.18](https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-dev.18/phet/curve-fitting_en_phet.html)  which is up-to-date as of right now. Please sign off for all supported platforms.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
---
- [ ] Win 7 chrome
- [ ] Win 7 firefox
- [ ] Win 7 internet explorer
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 safari
---
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 safari
---
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 safari
---
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 safari
---
- [ ] Mac 10.10 safari
---
- [ ] Chrome OS
---
- [ ] iOS 12
- [ ] iOS 11

**Comment by KatieWoe** [comment]
Possible Issues (will update comment as found):
* Win 10 Firefox.  Not bad, but the biggest cause of a loss of fps is when the curve is active and you are adjusting the error bars.  May help to have a larger number of points out.

**Comment by KatieWoe** [comment]
No iOS 11 devices in the office currently, but I'm fairly happy with this test as is.  Everything seemed acceptable to me.  @amanda-phet to confirm

**Comment by amanda-phet** [comment]
@KatieWoe are you wanting me to test on iOS11?

**Comment by KatieWoe** [comment]
@amanda-phet No, I think it is fine if we let it go without.  I wanted you to take a look on any platform and sign off on the performance as a designer.

**Comment by amanda-phet** [comment]
Gotcha. Thanks, I am happy with the performance I've seen on Mac OS 10.14.
