### ISSUE TITLE
Residual checkbox may not reset when reset all is used

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#161]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/423.
It is possible to reset all but still have the residual checkbox even though it doesn't appear to be.  Note, if you do not do step 5 bellow, residual resets fine.
**Steps to reproduce**
1. Refresh the sim page
2. Put two points out
3. Activate curve checkbox
4. Activate residual checkbox
5. Deactive curve checkbox
6. Hit reset all
7. Put two points out
8. Activate curve checkbox
9. Note that residual is still active

**Visuals**
![noresidualreset](https://user-images.githubusercontent.com/41024075/64730857-370c0780-d49d-11e9-8b21-7fb8243a1246.gif)
This is how a similar situation is handled in Wave Interference:
![WIhandle](https://user-images.githubusercontent.com/41024075/64730966-7fc3c080-d49d-11e9-8e31-9433adce2ba1.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Curve Fitting‬
URL: https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-dev.19/phet/curve-fitting_all_phet.html
Version: 1.0.0-dev.19 2019-09-04 19:08:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.75 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by SaurabhTotey** [comment]
I believe I fixed this in the previous commit in master. Assigning to @KatieWoe to review and sign off.

**Comment by KatieWoe** [comment]
Looks good on master
