### ISSUE TITLE
Design Suggestion: Adjustable Fit before Best Fit

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#163]
For https://github.com/phetsims/QA/issues/423
I noticed that, when you activate the curve checkbox, the best fit option is the default.  I think it might make more sense to make the adjustable fit default.  If a teacher's goal is to have students predict that line, the current option may flash the right answer before they can experiment (although admittedly only the linear option).

**Comment by amanda-phet** [comment]
That makes sense to me. However the learning goals aren't exactly about estimating the best fit, but instead comparing the values of X^2 and r^2 between different curves, and the change in those each time you add a term to the polynomial curve. Then the user can use adjustable fit to see how the best fit is determined.
