### ISSUE TITLE
Equation Pointer Area Dilated for mouse use

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/curve-fitting#164]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/431.  Very minor issue.
The pointer area for the equation's +/- button is dilated for both mouse and touch.  Normally, only touch is dilated.  This can be seen in the similar button for the X2 and r2 box.

**Visuals**
![inconsistentclickarea](https://user-images.githubusercontent.com/41024075/65530236-c6111a80-deb4-11e9-93b5-025b93b2f005.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Curve Fitting‬
URL: https://phet-dev.colorado.edu/html/curve-fitting/1.0.0-rc.1/phet/curve-fitting_all_phet.html?showPointerAreas
Version: 1.0.0-rc.1 2019-09-20 03:48:21 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by SaurabhTotey** [comment]
I just removed the mouse dilation for the equation accordion box's expand/collapse button on master.

**Comment by amanda-phet** [comment]
@KatieWoe please feel free to review the change. I'm fine with the suggestion.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
Looks good in rc.5
