### ISSUE TITLE
Drop down displays disappear if points in vertical line

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/curve-fitting#18]
Tested on OSX 10.9.6 Safari 7.0.6

Placing a certain number data points in a vertical line (dependent of the selection of linear, quadratic, cubic) all drop down displays, point container, and PhET menue disappear.

![screen shot 2015-05-19 at 9 45 20 am](https://cloud.githubusercontent.com/assets/5631059/7707428/fb28bef4-fe0c-11e4-9176-9a426c524b86.png)

To Reproduce:
Open Sim
Check curve 
Select Either (Linear, Quadratic, Cubic)
(Linear & Quadratic)
   Place 4 Points in a vertical line, i.e same x-component 
(Cubic)
   Place 5 Points in a vertical line, i.e same x-component 
The objects will disappear

Troubleshooting information (do not edit):
Name: Curve Fitting
URL: http://www.colorado.edu/physics/phet/dev/html/curve-fitting/1.0.0-dev.4/curve-fitting_en.html
Version: 1.0.0-dev.4 2015-05-18 16:31:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2
Language: en-us
Window: 1264x601
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.28.32)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"comment":"# curve-fitting 1.0.0-dev.4 Mon May 18 2015 10:31:50 GMT-0600 (Mountain Daylight Time)","curve-fitting":{"sha":"e701e0eb5ee5f5dfbbe194fcc31bbd52e354a238","branch":"master"},"assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"1199217e4b4a158afe5cf2fd59e5a7a087fd4179","branch":"master"},"babel":{"sha":"3ef6bce9237080ffa2d92c30d28b2d6f966bddc4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"8fd8eb6a428c4ea10ce8511af0f2cce6bfc61612","branch":"master"},"dot":{"sha":"9e70b8cac3ddfcb9e1dff786b23bc64de3b98350","branch":"master"},"joist":{"sha":"c9f2b67459f59f292a59bca7a714cd6f0908b4f9","branch":"master"},"kite":{"sha":"affd230ecc0d01f4f217ed7060007e3c71de4937","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"a69dfeb8452edb51348eb2187ce25939a8b0dda1","branch":"master"},"scenery-phet":{"sha":"4ca937ebfe35a021d4c781a4c6877be22ddbcf9b","branch":"master"},"sherpa":{"sha":"7c1f8f58b67a29014fb75ef4c80c3a5904193630","branch":"master"},"sun":{"sha":"5ae6c12634dc188f5b9ba8bc3aca76dcf96448c8","branch":"master"},"vegas":{"sha":"5d1f054ececac34752bbd2edcf940a6fdfdcb017","branch":"master"},"vibe":{"sha":"bad425472494babb88c260adbd718230d567ec3a","branch":"master"}}

**Comment by orejolaphet** [comment]
The objects locations still exist, that is the cursor changes when you hover over the locations of the objects, but are still not displayed.

**Comment by amanda-phet** [comment]
Is this a duplicate of #17 ?

**Comment by orejolaphet** [comment]
Oops. Yes, this is a duplicate of  issue https://github.com/phetsims/curve-fitting/issues/17.

Closing
