### ISSUE TITLE
Placing a data point behind the curve equation will disable movement of point

### ISSUE THREAD

**Issue by bryo5363** [phetsims/curve-fitting#22]
If you place a data point behind the drop-down window for the curve equation (top left), you will not be able to access that data point again

**Comment by bryo5363** [comment]
Place the point in the top left corner for best results

**Comment by amanda-phet** [comment]
@ariel-phet let's discuss this.

**Comment by amanda-phet** [comment]
The data point should be layered on top of the curve equation so that this does not happen.

**Comment by andrey-zelenkov** [comment]
Fixed equation overlapping by data points. Reassign to @bryo5363 for verification.

**Comment by amanda-phet** [comment]
This looks good so I'll go ahead and close it.
