### ISSUE TITLE
Default Adjustable Fit line is not displayed

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/curve-fitting#23]
Tested on OSX 10.9.4 Safari 7.0.5

The default adjustable fit line is not displayed once adjustable fit is checked. 

To reproduce:
Open sim
Click curve
Click Adjustable Fit

On the original sim:
![screen shot 2015-05-20 at 11 18 39 am](https://cloud.githubusercontent.com/assets/5631059/7732090/68dfb4e0-fee2-11e4-82b1-ce7a219b4edc.png)
HTML5:
![screen shot 2015-05-20 at 11 19 04 am](https://cloud.githubusercontent.com/assets/5631059/7732125/a79e790a-fee2-11e4-91fb-2380ff4c24b8.png)

**Comment by amanda-phet** [comment]
It seems like it only shows up after 2 points are added to the graph. The adjustable fit curve should always be visible, even if there are no points.

**Comment by andrey-zelenkov** [comment]
Fixed default visibility of Adjustable Fit. Reassign tot @orejolaphet for verification.

**Comment by amanda-phet** [comment]
This is working. Closing.
