### ISSUE TITLE
Issues with values displaying next to points

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#24]
Error and coordinates overlap at smallest error, values has to be checked:

![error coor](https://cloud.githubusercontent.com/assets/5863899/7773839/1b426970-0064-11e5-8af7-49487dd5ff68.PNG)

Tested on Win 8.1
Troubleshooting information:
Name: Curve Fitting
URL: http://www.colorado.edu/physics/phet/dev/html/curve-fitting/1.0.0-dev.4/curve-fitting_en.html
Version: 1.0.0-dev.4 2015-05-18 16:31:51 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# curve-fitting 1.0.0-dev.4 Mon May 18 2015 10:31:50 GMT-0600 (Mountain Daylight Time)","curve-fitting":{"sha":"e701e0eb5ee5f5dfbbe194fcc31bbd52e354a238","branch":"master"},"assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"1199217e4b4a158afe5cf2fd59e5a7a087fd4179","branch":"master"},"babel":{"sha":"3ef6bce9237080ffa2d92c30d28b2d6f966bddc4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"8fd8eb6a428c4ea10ce8511af0f2cce6bfc61612","branch":"master"},"dot":{"sha":"9e70b8cac3ddfcb9e1dff786b23bc64de3b98350","branch":"master"},"joist":{"sha":"c9f2b67459f59f292a59bca7a714cd6f0908b4f9","branch":"master"},"kite":{"sha":"affd230ecc0d01f4f217ed7060007e3c71de4937","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"a69dfeb8452edb51348eb2187ce25939a8b0dda1","branch":"master"},"scenery-phet":{"sha":"4ca937ebfe35a021d4c781a4c6877be22ddbcf9b","branch":"master"},"sherpa":{"sha":"7c1f8f58b67a29014fb75ef4c80c3a5904193630","branch":"master"},"sun":{"sha":"5ae6c12634dc188f5b9ba8bc3aca76dcf96448c8","branch":"master"},"vegas":{"sha":"5d1f054ececac34752bbd2edcf940a6fdfdcb017","branch":"master"},"vibe":{"sha":"bad425472494babb88c260adbd718230d567ec3a","branch":"master"}}

**Comment by amanda-phet** [comment]
When the error reaches 0.5, it is above the coordinates enough so that both are legible. Once the error is lower than 0.5 it starts to overlap. @ariel-phet I think we should discuss a constraint to implement here. Maybe the text moves with the bar until it is be low 0.5, at which point it stops moving with the bar?

**Comment by SaurabhTotey** [comment]
This is still an issue as of right now on master. I am assigning this issue to @ariel-phet to get an answer to the previous question so that I can know how to proceed.

**Comment by ariel-phet** [comment]
@SaurabhTotey I think we should make a few small tweaks. 

1. Currently (in master), the coordinates are not vertically centered on the data point (they are shifted up a bit versus the center line). Let's move the coordinates to be vertically centered.

2. Lets put a somewhat opaque box around the coordinates (lets try a light grey to begin with). For an example of what I mean, see the "Standard Form" screen of Graphing Quadratics and check the "Roots" checkbox

![gq](https://user-images.githubusercontent.com/4051174/58893329-2b928e80-86ad-11e9-9d5b-02313b022db5.PNG)


3. Let's enforce the constraint that @amanda-phet mentions above, so when reducing the error, the bars still move, but at around an error of 0.5 the bars still move but the error readout remains in a fixed position so no overlap occurs.

**Comment by SaurabhTotey** [comment]
I have now made it so that the error cannot overlap with the coordinates, and I have also added a background rectangle to the coordinates text. Also, the coordinates are now centered along the point. Below is an example of what points look like in master right now.

<img width="1381" alt="PointNode Changes Example" src="https://user-images.githubusercontent.com/22577113/58984805-290c6380-8797-11e9-9b67-d18b237556fc.png">

As such, I am marking this issue as ready for review.

**Comment by SaurabhTotey** [comment]
Assigning to @amanda-phet to review and potentially sign off on.

**Comment by amanda-phet** [comment]
The spacing looks great to me and it all looks good in terms of overlap. 

I like the gray background for the coordinates. I wonder if we can do a similar one for Dy, but give it a white transparent background. It would help in cases like this:
![image](https://user-images.githubusercontent.com/7852916/59455656-e4ee1400-8dd1-11e9-8483-053db6b9a4e2.png)

**Comment by amanda-phet** [comment]
Actually... can we also change the background of the coordinates from gray to orange, to match the point? If it looks like too much orange we can go back to gray, but I’d like to see it. Maybe you can try it and put in a screenshot here (I'm also happy to look in-person or on zoom with you).

**Comment by SaurabhTotey** [comment]
I still have yet to make the white semi-opaque background box for the Dy term. However, I switched the coordinates's background to orange. In the below screenshot, one of the point's coordinate background is fully opaque. The other point has a semi-opaque background for its coordinate. Both oranges are the same shade as the orange for the point.

<img width="641" alt="orange-point-example" src="https://user-images.githubusercontent.com/22577113/59468601-b67f3180-8def-11e9-98f9-71a5e0f7f92e.png">

**Comment by amanda-phet** [comment]
It should definitely not have full opacity... I can't remember what we decided on in Graphing Quadratics but maybe you could check that code and match it? Maybe .75? I can't remember at all.

**Comment by SaurabhTotey** [comment]
I just double checked to make sure, and both simulations use 0.75 for their opacities for these background rectangles. The point at (5, 5) is what the background rectangle looks like at 0.75 opacity.

**Comment by SaurabhTotey** [comment]
In my latest commit I added a white background for the delta text. The opacity of all background rectangles are 0.75. 

Currently, even when dragged outside of the graph area, the delta for points are visible, even though the coordinates are not. I am wondering whether this behaviour is desired. Another thing that happens that may not be desired is that when points animate back to the bucket, their coordinates reappear and update while they are over the graph.

Assigning to @amanda-phet to review changes and answer questions.

**Comment by amanda-phet** [comment]
The backgrounds look good to me. Thanks for adding those! 

I think it's fine for the error delta to be visible, since that seems consistent to me. I also noticed the coordinates on the point when returning to the bucket, and again that seems consistent to me and is fine. 

One thing that is very apparent now is the layering. Currently, newer points are layered over older points. It's a little strange when you are trying to view the values of an old point that is layered under a new point, because clicking the point doesn't "bring it to the top" of the layer order, which is what I expected to happen. This sounds tricky to solve. What do you think?

**Comment by SaurabhTotey** [comment]
At first, I thought it would be tricky, but it actually doesn't seem too hard to implement. The points that get clicked on get moved to the top now.

**Comment by amanda-phet** [comment]
Looks great to me! 

@ariel-phet do you have an opinion about the background colors? If you prefer gray I'm fine going back, but orange is consistent with what we are doing in other sims. Feel free to close if it looks good to you.

**Comment by ariel-phet** [comment]
@amanda-phet  Looks good to me. Closing
