### ISSUE TITLE
Residuals terminate early

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#27]
The cause of this is very much #15, but this ticket gets more specific for multitouch devices.
1. Check "Curve" and "Residuals".
2. Drag on four or more points.
3. Choose "Cubic" then "Adjustable fit".
4. With one finger start dragging the "a" slider and with another finger go to "Quadratic". #15 happens.
5. Continue to drag your first finger around that's controlling the "a" slider, the residuals behave as though the curve is quadratic:

![img_0009](https://cloud.githubusercontent.com/assets/5863899/7775535/2e8c7928-0071-11e5-8847-4e81cb3753c1.PNG)

Tested on iPad Air 2, iOS 8.3

**Comment by phet-steele** [comment]
Troubleshooting information (do not edit):
Name: Curve Fitting
URL: http://www.colorado.edu/physics/phet/dev/html/curve-fitting/1.0.0-dev.4/curve-fitting_en.html?showPointerAreas
Version: 1.0.0-dev.4 2015-05-18 16:31:51 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 768x928
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"comment":"# curve-fitting 1.0.0-dev.4 Mon May 18 2015 10:31:50 GMT-0600 (Mountain Daylight Time)","curve-fitting":{"sha":"e701e0eb5ee5f5dfbbe194fcc31bbd52e354a238","branch":"master"},"assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"1199217e4b4a158afe5cf2fd59e5a7a087fd4179","branch":"master"},"babel":{"sha":"3ef6bce9237080ffa2d92c30d28b2d6f966bddc4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"8fd8eb6a428c4ea10ce8511af0f2cce6bfc61612","branch":"master"},"dot":{"sha":"9e70b8cac3ddfcb9e1dff786b23bc64de3b98350","branch":"master"},"joist":{"sha":"c9f2b67459f59f292a59bca7a714cd6f0908b4f9","branch":"master"},"kite":{"sha":"affd230ecc0d01f4f217ed7060007e3c71de4937","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"a69dfeb8452edb51348eb2187ce25939a8b0dda1","branch":"master"},"scenery-phet":{"sha":"4ca937ebfe35a021d4c781a4c6877be22ddbcf9b","branch":"master"},"sherpa":{"sha":"7c1f8f58b67a29014fb75ef4c80c3a5904193630","branch":"master"},"sun":{"sha":"5ae6c12634dc188f5b9ba8bc3aca76dcf96448c8","branch":"master"},"vegas":{"sha":"5d1f054ececac34752bbd2edcf940a6fdfdcb017","branch":"master"},"vibe":{"sha":"bad425472494babb88c260adbd718230d567ec3a","branch":"master"}}

**Comment by amanda-phet** [comment]
Let's revisit this after #15 is addressed.

**Comment by veillette** [comment]
Since we rewrote the graphareanode, this issue doesn't apply anymore. Closing
