### ISSUE TITLE
Mouseover/Tap behavior

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#29]
The design document included a section about a behavior for when a cursor is hovering over a point or error bar. This still needs to be implemented.
![screen shot 2015-06-01 at 10 54 59 am](https://cloud.githubusercontent.com/assets/7852916/7918200/d4fe2102-084c-11e5-8ebc-ff69c2270583.png)
![screen shot 2015-06-01 at 10 56 42 am](https://cloud.githubusercontent.com/assets/7852916/7918204/e304eefc-084c-11e5-9610-914b3e1861aa.png)

**Comment by andrey-zelenkov** [comment]
Added halo for error bars and point. Reassign to @amanda-phet for verification.

**Comment by amanda-phet** [comment]
Looks good except for the bars. If the mouse hovers over one of the error bars, *both* should highlight to indicate that both will move. (This is important for touch use).

**Comment by andrey-zelenkov** [comment]
Both error bars are highlights on hover event. Reassign to @amanda-phet for verification.

**Comment by amanda-phet** [comment]
Looks good. Closing.
