### ISSUE TITLE
create curve-fitting-screenshot.png

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#32]

**Comment by jonathanolson** [comment]
Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by pixelzoom** [comment]
A little premature to do this until the sim is nearer to completion. (Imo, this shouldn't be in the code review checklist, since it's in the master checklist.)

**Comment by amanda-phet** [comment]
Seems this was done via https://github.com/phetsims/curve-fitting/commit/0f1a686e8ecfadc78b67d92870519b3e2d18c202 .
