### ISSUE TITLE
Fill in credits

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#34]
Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by pixelzoom** [comment]
@amanda-phet can you please fill in the sim credits?  If any of these categories are irrelevant for this sim, you can omit them.  

```
    credits: {
      leadDesign: '',
      softwareDevelopment: '',
      team: '',
      qualityAssurance: '',
      graphicArts: '',
      thanks: ''
    }
```

Credits for the Java version were:

```
PhET Development Team
Lead Design: Michael Dubson
Software Development: Michael Dubson
Design Team: Trish Loeblein
```

I'm not sure who has participated in the HTML5 development, perhaps @ariel-phet knows.

**Comment by pixelzoom** [comment]
Looks like MLL did initial work on the HTML5 version.  Should the 'thanks' category include:

```
'Thanks to Mobile Learner Labs for working with the PhET development team to convert this\nsimulation to HTML5.'
```

**Comment by amanda-phet** [comment]
credits: {
  leadDesign: 'Mike Dubson, Amanda McGarry',
  softwareDevelopment: 'Chris Malley, Jonathan Olson, Martin Veillette',
  team: 'Trish Loeblein, Ariel Paul, Kathy Perkins',
  qualityAssurance: '',
  graphicArts: '',
  thanks: 'Thanks to Mobile Learner Labs for working with the PhET development team to convert this simulation to HTML5.'
}

I may come back and edit this (at least for the QA section), but I wanted to get it started. Leaving this assigned to me until these are finalized.

**Comment by pixelzoom** [comment]
Thanks @amanda-phet. I've added what you provided so far, can fill in the rest later.  FYI, I added Mike Dubson to the softwareDevelopment category, since he was the author of the original Flash version.

**Comment by amanda-phet** [comment]
Unassigning. @phet-steele should add in QA credits when this sim is closer to publication.

**Comment by amanda-phet** [comment]
We need to add Saurab to the list of Developers! 

@KatieWoe can you add QA credits?

**Comment by amanda-phet** [comment]
@ariel-phet  should we still be thanking MLL? They did work on it, but I'm not sure they were all that helpful...

**Comment by KatieWoe** [comment]
https://github.com/phetsims/QA/issues/439#issuecomment-544676226
QA credits here

**Comment by ariel-phet** [comment]
@amanda-phet yes, we should still thank MLL, the did do the initial work, and I believe it was part of our contractual obligation, so best to just put it in there.

**Comment by SaurabhTotey** [comment]
Credits are up-to-date on master and 1.0. Closing.
