### ISSUE TITLE
Bad layout on stringTest=double

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#35]
![screen shot 2015-08-04 at 11 16 16 am](https://cloud.githubusercontent.com/assets/480878/9067390/599b47f8-3a9a-11e5-8585-d1de5c795639.png)

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Fixed layout with long strings. Reassign to @jonathanolson for verification/

**Comment by jonathanolson** [comment]
Looks great, thanks!
