### ISSUE TITLE
Some adjustable fit values return to default when switching between curve types

### ISSUE THREAD

**Issue by phet-steele** [phetsims/curve-fitting#36]
This is present in the Flash version. The sliders for "a" and "b" on the Cubic curve and the slider for just "b" on the Quadratic curve return to a default value after sliding them and switching between curve types:

![curfi](https://cloud.githubusercontent.com/assets/5863899/9179091/6aca40a8-3f57-11e5-8c7c-b8aa3338818a.gif)

 It would be nice if these values that were set by a user remained there in the use case of someone comparing two fits on the same set of points. Currently, the user loses their adjustable fit and has to remake it upon switching curve types. Up to @ariel-phet or @amanda-phet to decide where to proceed with this, since it's also in Flash.

**Comment by memo330179** [comment]
Assigning to @veillette for review

**Comment by pixelzoom** [comment]
This was still messed up. Fixed in 8e6c957197ca29abdfad3b2c607a082dd48a4e22. Closing.
