### ISSUE TITLE
Instance references should not be capitalized

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#38]
E.g. ```CurveFittingModel``` should refer to the constructor of the type, and ```curveFittingModel``` should refer to an instance of the CurveFittingModel.

It's very confusing to have a capitalized name refer to an object instance rather than a type.

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Instance references uncapitalized. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
