### ISSUE TITLE
What is the point of the NaN values for points?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#39]
It seems like an anti-pattern, and I wasn't easily able to determine what they were being used for.

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
It was necessary to determine situation when the point is outside the graph (coordinates isn't important in this case, so it's set to NaN). If NaN should be eliminated then we can calculate coordinates for every point position and add some extra checks, but imho adding description to clarify this moment can be enough.

**Comment by andrey-zelenkov** [comment]
NaN values were removed during fixing #48 (9bbea0b45fd6f4cc86fee05a861ce905b4fb135a). It was replaced by 'isInsideGraph' flag.

**Comment by jonathanolson** [comment]
Looks good, thanks.
