### ISSUE TITLE
isFinite returns false for NaN

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#40]
So no additional ```isNaN( x ) || isFinite( x )``` checks are needed, ```isFinite( x )``` is sufficient.

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Fixed via 6a0430bdc0fcc2e38021661bf4389c04e8d7bacb. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
