### ISSUE TITLE
Parenthesis code style doesn't match

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#42]
There should be spaces inside parenthesis as a general rule, so instead of:
```js
(chiValue - lowerBound) / (step4 - lowerBound)
```
it should be:
```js
( chiValue - lowerBound ) / ( step4 - lowerBound )
```

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Fixed parenthesis code style. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
