### ISSUE TITLE
Recommend Curve getValueAt( x ) method

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#43]
Lots of model-specific code for determining a curve's value at a certain location is in less relevant places (e.g. GraphAreaNode).

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by jonathanolson** [comment]
This should be fairly minor, I'll take care of it after other review items.

**Comment by veillette** [comment]
curve.getYValueAt( x ) was added. It is used in GraphAreaNode.

**Comment by veillette** [comment]
Work is done here. Closing
