### ISSUE TITLE
Documentation of types in methods

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#44]
It would be helpful to have type documentation for types in many method calls (similar to constructors). For example, I'm left wondering when reviewing "Is 'point' a Vector2 or Point"?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Added documentation of types in methods. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
