### ISSUE TITLE
Type documentation for ObservableArray

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#45]
Documentation for parameters/objects of type ObservableArray should include the type of the element (like {ObservableArray.<Point>}).

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Added type documentation for ObservableArray. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Thanks!

I'll look into some renaming, like with pointsProperty:
```js
// @param {ObservableArray.<Point>} pointsProperty - Array of points for plotting curve.
```

**Comment by veillette** [comment]
The documentation was added. In addition the observable array was renamed points, throughout the simulation.

**Comment by veillette** [comment]
Closing
