### ISSUE TITLE
Model-view transforms

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#46]
It's typical to have a ModelViewTransform2 between model-view space, instead of the non-standard CurveFittingConstants.PIXELS_IN_TICK, as it helps not just with scale, but positioning as well.

I'd recommend following the usual model-view transform usage for PhET simulations.

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
CurveFittingConstants.PIXELS_IN_TICK was removed in a33487fcfbf809cfd8969d2526f0489d05331982 and ModelViewTransform2 was implemented in 43492380ef66131bfa1369ad17eeb6e5e2e893d1. Reassign to @jonathanolson for verification.

**Comment by veillette** [comment]
Although there is currently a modelViewTransform, it is set to identity throughout the sim. We will work into it.

**Comment by veillette** [comment]
Work is done here. Closing
