### ISSUE TITLE
Behavior of adjustable fit selection

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#47]
Why does toggling "Curve" visibility reset the adjustable fit, but switching between best/adjustable doesn't?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Remembering while switching between best/adjustable was discussed earlier in https://github.com/phetsims/curve-fitting/issues/13#issuecomment-107691750. Resetting while toggling "Curve" is came from original sim (when we select "no fit" in original sim it's also reset adjustable fit).

**Comment by jonathanolson** [comment]
Thanks! Removing review label, and assigning to @amanda-phet to decide if we also want to safe the adjustable fit when we toggle the "Curve" visibility.

**Comment by pixelzoom** [comment]
@amanda-phet specified the desired behavior for this in https://github.com/phetsims/curve-fitting/issues/89, where this issue will now be tracked.

Closing./
