### ISSUE TITLE
Point position properties

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#48]
There is point.position (I've inferred this is the global screen coordinate of the point where it was last located), and point.x/point.y (the actual model location). Is that correct (and if so, can it please be documented)?

Additionally, it seems suspicious to be storing the last global coordinate of a view's point in the model. I haven't fully worked out the logic of how it doesn't break when the sim is resized, but can you make a good case for why global screen-position of view elements is stored in the point's model?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by jonathanolson** [comment]
Also why does Point.moveTo only modify position?

**Comment by andrey-zelenkov** [comment]
Removed point positionProperty from model. Also removed Point.moveTo function. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Thanks!
