### ISSUE TITLE
"Question Mark" button does not function

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/curve-fitting#5]
In this sim, pressing the question mark button in the left control panel is supposed to open up a dialog box with a description of the formula used for calculations. This formula box is described in the specification for the simulation.

**Comment by andrey-zelenkov** [comment]
I have question about implementing dialog box. Should it be done using JOIST/Dialog.js or JOIST/OptionsDialog.js? When I try to create dialog node using one of this components, for example: 

    Dialog.call( this, content, {
      modal: true,
      hasCloseButton: false
    } );

I'm getting "TypeError: Cannot read property 'center' of null" (Dialog.js line 133): 

    dialog.center = simBounds.center.times( 1.0 / scale );

I've tried to pass bounds like options in simOptions (curve-fitting-main.js) and ScreenView options (CurveFittingView.js) but without success. I will be grateful for help.

**Comment by jonathanolson** [comment]
First of all, JOIST/Dialog should be the correct choice (don't want "Options" text included at the top).

Second, the dialog should not be added to the parent node, especially at creation. It should use the pattern to be shown:
```js
new SomeDialog().show();
```

I saw commented out that it was being created and added when the original parent was created, and it looks like this causes an error because the sim hasn't been fully set up yet.

Let me know if there's anything else with this that I can do to help.

**Comment by andrey-zelenkov** [comment]
I've added help menu but I have question about text description below the formula. Should "N" and "f" signs converted to images and integrated into other text or is there a better way?

**Comment by jonathanolson** [comment]
Yes. To copy-paste from the implementation details from the Curve Fitting HTML5 doc:

> The dialog with the formulas and text should use Dialog. The formula itself and the formula fragments (in italic, like "N", "f", "f=4") should be converted into images, generated in TeX/LaTeX, with something similar to \chi_r^2=\frac{1}{N-f}\sum_{i}\frac{\left| y(x_i) - y_i \right|^2}{\sigma^2_i}. To combine the translated text ("for a cubic fit", etc.) and the fragments (images), HTMLText nodes should be used, using replacements ({0}) for the images where necessary.

**Comment by andrey-zelenkov** [comment]
And one more question: I've tried to insert image into HTMLText using replacement, but I've got next result: 

![screen shot 2015-05-14 at 21 48 34](https://cloud.githubusercontent.com/assets/3500611/7639248/2ba61ef6-fa83-11e4-90b6-166b5a7684b8.png)

I've tried to wrap image into new Image() but without success. What could be the reason?

**Comment by jonathanolson** [comment]
Try adding in ```'<img src="' + image.src + '">'```.

**Comment by andrey-zelenkov** [comment]
Thanks a lot Jonathan! Added help dialog for question button. Reassign to @ariel-phet for verification.

**Comment by ariel-phet** [comment]
Functioning now...but the images are low quality, perhaps we could use mipmapping here?

**Comment by ariel-phet** [comment]
@jonathanolson can you take a look at this implementation - the images for the equations are really aliased.

**Comment by jonathanolson** [comment]
The raw images are not at all high enough resolution, they will need to be updated:
![screen shot 2015-05-28 at 11 50 16 am](https://cloud.githubusercontent.com/assets/480878/7866959/280c260c-0530-11e5-8b64-cda80f1ceed6.png)

**Comment by andrey-zelenkov** [comment]
Image resolution improved. Reassign to @ariel-phet for verification.

**Comment by ariel-phet** [comment]
Looks *MUCH* better, thanks!
