### ISSUE TITLE
Naming in CurveFittingModel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#50]
Some recommended name changes that seem more grammatical:

isResidualsVisible => areResidualsVisible

isValuesVisible => areValuesVisible

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Fixed naming in CurveFittingModel. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
