### ISSUE TITLE
CurveFittingModel's maxOrderOfFit

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#51]
This seems like a global that should be accessed as CurveFittingModel.maxOrderOfFit, since it never changes, and isn't specific to a specific model (as it has to be passed around places in the code).

Can the instance property be changed to a global?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
MaxOrderOfFit moved to constants. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
