### ISSUE TITLE
Model-view separation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#52]
It seems like a lot of view state (visibility of curves/residuals/values and whether panels are expanded, and global screen position of points) is stored in the model.

This type of information should generally be stored in the view (e.g. CurveFittingModel/PointNode), since it doesn't describe the underlying model.

Is there a reason this information is in the model currently?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by jonathanolson** [comment]
Also chiFill on the Curve (a color for the view) seems like part of the view, not the model.

**Comment by andrey-zelenkov** [comment]
Visibility of curves/residuals/values and panels expanding often necessary for optimizations (for example if deviation panel is collapsed then we can disable calculating chi-values and colors). It was done based on the experience of creating the previous simulations. chiFill can be moved to view without harm.

**Comment by andrey-zelenkov** [comment]
chiFill calculations moved to view. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Will handle myself, MVT shouldn't be identity.

**Comment by veillette** [comment]
The model view transform is currently being passed around but is set as Identity, and not being used. We will look into making the bounds the graph from (-10 to 10 in x and y), the model bounds and used the model view transform to get the positions in the view.

**Comment by veillette** [comment]
The position of points is now done in the model, and the modelviewtransform is used throughout the simulation.

**Comment by veillette** [comment]
All of the visibility flags are in the model, and indeed there is a performance benefit associated with many of them. At that point it seems reasonable to have all of them in the model.

**Comment by veillette** [comment]
I think it is a reasonable compromise. Closing
