### ISSUE TITLE
Inlining of CurveFittingModel.getPoint?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#53]
It has one usage, and is very simple. Any arguments against inlining its one usage?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Made inlining of CurveFittingModel.getPoint function. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
