### ISSUE TITLE
Naming of Curve properties

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#54]
_orderOfFit and _fitType are both properties, so it seems clearer if they had the 'Property' suffix (as is very typical for properties).

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Added Property suffix to _orderOfFit and _fitType variables. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
