### ISSUE TITLE
Curve _storage

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#57]
It's unclear to me (without documentation) what _storage is for, and how exactly best/adjustable values are initialized/set/moved to storage/moved from storage, etc.

Can this be clearly documented?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Added _storage documentation in Curve. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Thanks!
