### ISSUE TITLE
Curve updateCurveTrigger

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#58]
Instead of using a Property as a way of sending events, just use curve.trigger/curve.on/curve.off (Curve is a PropertySet, which inherits Events, which provides lots of great ways to listen to and trigger events).

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Replaced updateCurveTrigger property by default trigger. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
