### ISSUE TITLE
Curve top-level functions

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#59]
Usually all of the content that is between Curve's constructor and its inherit() call would exist above the constructor (so they are defined above the constructor where they might be used). It looks like 'var f = function(...){...}' is being used instead of 'function name(...){...}" to bypass a linting failure since the function is declared below the usage (the var causes it to be hoisted above).

Can this code be moved in front of the constructor, and be converted back to the normal "function name(){}" form?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Private functions in Curve model moved in front of the constructor, also changed declaration. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
