### ISSUE TITLE
Curve fit listeners

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#60]
There is a lot of code dedicated to adding/removing updateFitBinded based on whether the curve is best/adjustable.

It seems simpler to always have a listener attached, where the listener checks the fitType (and only runs things if it is adjustable). Thoughts?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
No, it was made for optimization (to prevent extra updateFit calls when fit type is adjustable). There are necessary "if" condition is already present in updateFit function. Removed linking/unlinking of curve parameters while mode switching. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Removing review tag, will look into it.

**Comment by veillette** [comment]
This issue is irrelevant since the simulation does no longer make use of properties to keep track of the parameter a, b, c ,d.
All the code regarding saving, deleting and stashing status of properties has bee removed.
