### ISSUE TITLE
Documentation for Curve

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#61]
lowerLimitArray, upperLimitArr (why Array/Arr?) and getBarometerFillFromChiValue in particular could use documentation to help clarify their purpose, and how they work.

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Function and arrays were copied into BarometerX2Node (bd9f1cebaa06d234f6e57f8e0d67e8cca3dbae71) and renamed. Added documentation for getChiFillFromChiValue function and arrays. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Thanks.
