### ISSUE TITLE
DeviationsNode name

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#63]
Typically if it's a Panel used as a control panel, we'd call it "DeviationsPanel". "DeviationsNode"'s name let me to think it was displaying residuals.

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
DeviationsNode renamed into DeviationsPanel. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
