### ISSUE TITLE
BucketNode

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#64]
We have standard code for displaying buckets in scenery-phet, so that sims are consistent. Is there any reason this code for displaying the bucket shouldn't be used? (Just the bucket, not what is in it).

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Replaced painting bucket node by standard scenery-phet component. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Bucket use looks good, but isn't the clipping not needed? It should be possible to put the pointsNode under the BucketFront, and in front of the BucketHole, so that it's not needed.

**Comment by andrey-zelenkov** [comment]
Good point, thank you! Removed clip shape for points. Reassign to @jonathanolson for verifcation.

**Comment by jonathanolson** [comment]
Looks good, thanks!
