### ISSUE TITLE
GraphAreaNode simplifications

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#65]
For a Bounds2, ```bounds.maxX - bounds.minX``` is equivalent to ```bounds.width```, which could simplify some lines in this file.

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Made some code simplifications. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
