### ISSUE TITLE
GraphAreaNode documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#66]
Top-level documentation notes that it contains points. It doesn't seem to include points.

Can the documentation be updated/clarified?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Fixed GraphAreaNode documentation. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks.
