### ISSUE TITLE
GraphAreaNode isContainsPoint

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#67]
For improved grammar and clarity, could I suggest renaming it to isPointInsideGraph()?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Renamed method isContainsPoint in isPointInsideGraph. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
