### ISSUE TITLE
PointNode's pointModel documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#68]
It notes:
```
@param {PropertySet} pointModel - Model for single point.
```

Should this be ```{Point}``` instead?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Fixed pointModel type description. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
