### ISSUE TITLE
PointNode halos and bars

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#69]
Constructing rectangles in PointNode would be a bit clearer by first constructing Bounds2 instances, and then using the various dilation functions to get larger (expanded) copies of the bounds (then Rectangle.bounds( bounds) could be used).

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Made refactoring for PointNode halos and bars. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
