### ISSUE TITLE
Curve does not reflect values in equation or slider

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#7]
The sliders seem to be correctly manipulating the equation, but the curve itself is incorrect. It looks like the values are negated- if c = 2.4785, the curve is graphed with c = -2.4785. This seems to be a problem for all curves that are created with the adjustable fit sliders. 

![screen shot 2015-04-22 at 9 29 27 am](https://cloud.githubusercontent.com/assets/7852916/7278476/f3c07a8e-e8d2-11e4-802c-6710c0d9a1f7.png)

**Comment by andrey-zelenkov** [comment]
Fixed inverting of y-axis. Reassign to @amanda-phet for verification.

**Comment by amanda-phet** [comment]
This does not appear to be fixed.

**Comment by andrey-zelenkov** [comment]
The angle of the curve changed for me. Are you still can reproduce angle from screenshot above? Or can you clarify issue (perhaps I misunderstood what need to be done)? Now it  looks for me:

![screen shot 2015-05-07 at 21 23 29](https://cloud.githubusercontent.com/assets/3500611/7522655/5ba7db82-f4ff-11e4-9281-a4d789294640.png)

**Comment by amanda-phet** [comment]
This looks fixed now. Thanks!
