### ISSUE TITLE
CurveFittingView duplicated reference

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#70]
Could the duplicate ```new Bounds2( 0, 0, 768, 504 )``` be factored out to reference SIM_BOUNDS?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
Removed duplicated reference. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
