### ISSUE TITLE
Adjustable fit sliders have overlapping touch areas

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#72]
Can the touch areas be slightly less wide so that they are flush?

Review: https://github.com/phetsims/curve-fitting/issues/31

**Comment by andrey-zelenkov** [comment]
I'm using SUN/HSlider to draw slider and I can't find any option to change touch areas of default thumb. Also I can't find default ThumbNode module to pass it using thumbNode option. Should all code related to ThumbNode be copied form HSlider to adjustable sliders class? Or there other way to change size of touch areas?

**Comment by jonathanolson** [comment]
Removing 'review' label, I'll take care of this one. Will ask in developer meeting about standard ways of handling touch areas for this.

**Comment by jonathanolson** [comment]
Plan to create default thumb, change touch areas, and pass it through as a custom thumb.

**Comment by jonathanolson** [comment]
Or... just provide public access to the thumb. Probably that.

**Comment by jonathanolson** [comment]
Decided on dot.Insets, and integration with bounds modifiers. Add thumbMouseAreaInsets and thumbTouchAreaInsets as options, that will only modify the default behavior.

**Comment by Denz1994** [comment]
Adjusted slider touch area parameters by changing the HSlider options. Made possible by https://github.com/phetsims/sun/commit/c5dbf7cdfa530d559f8d1ded3d9714d84a5c3570

**Comment by pixelzoom** [comment]
I will review this as part of a more general test of pointer areas.

**Comment by SaurabhTotey** [comment]
Touch areas are now flush for adjustable fit sliders.

<img width="226" alt="Slider Touch Areas" src="https://user-images.githubusercontent.com/22577113/59627405-652ab700-90fb-11e9-8289-d8d0993afdb7.png">
