### ISSUE TITLE
Can we avoid using translatable strings in HTMLText?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/curve-fitting#74]
See https://github.com/phetsims/special-ops/issues/18. If using them is a requirement, then let me know (I'll need to look into sanitization of translated strings).

**Comment by veillette** [comment]
Currently, there is only one usage of HTMLText in curveFitting. It Makes uses of one string (a pattern).



```
    var patternNumberOfParametersInFitEG0ValueForACubicFitString = require( 'string!CURVE_FITTING/pattern.numberOfParametersInFitEG.0value.ForACubicFit' );
```

```
  "pattern.numberOfParametersInFitEG.0value.ForACubicFit": {
    "value": "number of parameters in fit (e.g. {0} for a cubic fit)"
  },
```
in DeviationPanel.js
```
          new HBox( {
            children: [
              new Image( fSymbolImage, { scale: IMAGE_SCALE } ),
              new HTMLText( '= ' + StringUtils.format(
                  patternNumberOfParametersInFitEG0ValueForACubicFitString,
                            '<img style="vertical-align: bottom; width:' + parseInt( fEqualFourImage.width * IMAGE_SCALE, 10 ) + 'px" src="' + fEqualFourImage.src + '">'
                ),
                { font: TEXT_DIALOG } )
            ]
          } )
``

**Comment by veillette** [comment]
Although we used SubSupText extensively. 
There is a issue tracking it, here.  https://github.com/phetsims/scenery/issues/528

**Comment by pixelzoom** [comment]
> Although we used SubSupText extensively. 

SubSupText is a little different than HTMLText. We're not trying to use the browser to render HTML, we're simply using HTML as the markup language. SubSupText parses the string, and creates (and lays out) separate scenery.Text nodes for the subscript, superscript and "base" parts of the string.

The issue in phetsims/scenery#528 is a speed bump that will presumably be addressed when @jonathanolson returns from leave.  It concerns a security issue, not a rendering issue.

**Comment by pixelzoom** [comment]
Looks trivial to make this HTMLText unnecessary.  Simply use Unicode for the mathematical 𝑓 (`'\u1D45e'`), i.e.:

```js
"pattern.numberOfParametersInFit": {
    "value": "\u1D45e = number of parameters in fit (e.g. \u1D45e = 4, for a cubic fit)"
  },
```

**Comment by pixelzoom** [comment]
Drat. Mathematical 𝑓 is one of those multibyte characters that requires a font that supports it - which we do not have by default.

**Comment by pixelzoom** [comment]
Having to use HTMLText and image files for math symbols is totally bogus.  So I've removed those, and have implemented something that works on desktop browsers.  I will need to confirm on iPad, to verify that the mathematical Unicode symbols are supported.  And if I run into problems, I'm sure that I can come up with something else.  So... Leaving this issue open to verify on iPad.

**Comment by pixelzoom** [comment]
Looks decent on desktop, e.g. Chrome:

![screenshot_67](https://cloud.githubusercontent.com/assets/3046552/17156439/181917a8-5347-11e6-962d-78c4b09fee2c.png)

The top equation is still an image, which I'll address separately in https://github.com/phetsims/curve-fitting/issues/82.

**Comment by pixelzoom** [comment]
As I feared, the Unicode mathematical 'N' and 'f' symbols are not displayed on iPad, because there is no font support.  Same as this https://github.com/phetsims/function-builder/issues/28 that was encountered in function-builder.  So this is currently broken on iPad, and will be until I get around to fixing it.

**Comment by pixelzoom** [comment]
I resolved this by using scenery-phet.MathSymbolFont for the 'f' and 'N' symbols, and that works on all platforms.  

Since the font for the symbols (MathSymbolFont) must be different that the font for the rest of the text (PhetFont), this results in i18n limitations.  For example, the "f = ...."  must be assembled as 4 fragments.  Eg for English, the 4 fragments are:

```
new Text( 'f', { font: new MathSymbolFont() } )
new Text( '= number of parameters in fit (e.g.', { font: new PhetFont() } )
new Text( 'f', { font: new MathSymbolFont() } )
new Text( '= 4, for a cubic fit)', { font: new PhetFont() } )
```

Those 4 fragments are then assembled left-to-right (using HBox).  And that assembly is the part that is not adaptive to locale.

**Comment by pixelzoom** [comment]
Allowing the translator to control the layout of nodes is a general problem (and a large-ish project) which I've move to https://github.com/phetsims/scenery-phet/issues/251.  For the time being, I'm not going to address this issue in curve-fitting.

**Comment by pixelzoom** [comment]
The original issue (avoiding use of HTMLText) has been addressed.  And I've moved the issue of text layout to https://github.com/phetsims/curve-fitting/issues/91.

Closing.
