### ISSUE TITLE
Point Creation in top left corner

### ISSUE THREAD

**Issue by Denz1994** [phetsims/curve-fitting#75]
Clicking in the top left most corner of the sim generates a new point that can be placed on the graph. This occurs right around the expand button for the Deviations box on the left side of the sim. There is no indication that this should happen in the simulation and is assumed to be a bug.

![image](https://cloud.githubusercontent.com/assets/13894380/16463631/9be45e56-3e04-11e6-862e-b364e5b4a616.png)

**Comment by veillette** [comment]
This should addressed the problem. Closing.
