### ISSUE TITLE
Calculation of r^2 

### ISSUE THREAD

**Issue by veillette** [phetsims/curve-fitting#77]
The r^2 value is not a very well defined quantity for non-linear, weighted and non-optimal fits.

Currently it is given by

``` js
    // set r^2-deviation for current point
    setRSquared: function() {
      var points = this.getPoints();
      var rSquare;
      var ySum = 0;
      var yDelta = 0;
      var yDeviation;
      var pointsLength = points.length;

      for ( var i = 0; i < pointsLength; ++i ) {
        ySum = ySum + points[ i ].y;
      }

      ySum = ySum / pointsLength;

      for ( i = 0; i < pointsLength; ++i ) {
        yDeviation = points[ i ].y - ySum;
        yDelta = yDelta + yDeviation * yDeviation;
      }

      rSquare = 1 - this.yDeviationSquaredSum / yDelta;

      if ( rSquare < 0 || isNaN( rSquare ) ) {
        this.rSquare = 0;
      }
      else {
        this.rSquare = rSquare;
      }
    },

```

Notice the last part of the algorithm, where any values of r^2 that are negative are set to zero.
In addition, it does not take into account the weight of a point.

**Comment by veillette** [comment]
Assigning to myself.
some references

- http://www.graphpad.com/support/faqid/1355/
- https://github.com/scikit-learn/scikit-learn/blob/51a765a/sklearn/metrics/regression.py#L370
- http://pubs.usgs.gov/tm/tm4a8/pdf/TM4-A8.pdf

**Comment by veillette** [comment]
![image](https://cloud.githubusercontent.com/assets/7633344/16569080/1b1c9e00-4200-11e6-975b-1f09c72c7996.png)

![image](https://cloud.githubusercontent.com/assets/7633344/16569073/0e66aa98-4200-11e6-94cc-dc46f18eabee.png)

**Comment by veillette** [comment]
There was no r^2 barometer in the original flash simulation

**Comment by amanda-phet** [comment]
r^2 was calculated in the original sim, we just changed the representation to be a "barometer". 
![screen shot 2016-07-21 at 12 00 43 pm](https://cloud.githubusercontent.com/assets/7852916/17033313/ce774b52-4f3a-11e6-9126-c260b34ec172.png)

r^2 should always be positive, so I'm not sure why there is a line of code for when it is negative.

**Comment by veillette** [comment]
Thanks @amanda-phet, 
I undertand that @samreid has a way to access the flash code of our previous simulations. 
Can you copy paste the code for curve-fitting below.

**Comment by ariel-phet** [comment]
@samreid since you did this for projectile motion, could you do the same for @veillette here and paste the relevant code in the issue?

**Comment by samreid** [comment]
It looks like those actionscript files are already externalized (top level files, not embedded in the fla), and you can see them here: https://phet.unfuddle.com/a#/projects/9404/repositories/23262/browse?path=%2Ftrunk%2Fsimulations-flash%2Fsimulations%2Fcurve-fitting%2Fsrc

Please report back if you find what you need there.

**Comment by veillette** [comment]
Thanks @samreid

**Comment by veillette** [comment]
Here is the relevant portion of code
```
   function setReducedChiSquare():Void{
        var a:Number = this.fitParameters[0];
        var b:Number = this.fitParameters[1];
        var c:Number = this.fitParameters[2];
        var d:Number = this.fitParameters[3];
        var e:Number = this.fitParameters[4];
        var N:Number = this.nbrPoints;
        var sum:Number = 0;
        var pointsRef_arr = this.points_arr;
        var yOnCurveRef_arr = this.yOnCurve_arr;
        var modelRef = this;
        this.SSerr = 0; //SSerr used to compute r^2 correlation coefficient
        if(orderOfFit == 0){
            sum = 0;
        }else if(N > this.orderOfFit +1){
            sum = computeSum();
        }else{
            sum = 0;
            //set yOnCurve_arr
            if(this.fitOn){
                for(var i:Number = 0; i < N; i++){
                    yOnCurveRef_arr[i] = pointsRef_arr[i].yPos;
                }
            }else{ //if fit adjustable, update yOnCurve_arr by calling computeSum()
                sum = computeSum();
            }
        }
                 
        function computeSum():Number{
            sum = 0;
            for(var i:Number = 0; i < N; i++){
                var yi:Number = pointsRef_arr[i].yPos;
                var xi:Number = pointsRef_arr[i].xPos;
                var xiSq:Number = xi*xi;
                var sigma:Number = pointsRef_arr[i].deltaY;
                var yFit = a + b*xi + c*xiSq + d*xi*xiSq + e*xiSq*xiSq ;
                this.yOnCurveRef_arr[i] = yFit;
                //trace("i: " + i + "   this.yOnCurveRef_arr[i]:" + this.yOnCurveRef_arr[i]);
                //trace("i:"+i+"   yi:"+yi+"   yFit:"+yFit+"   sigma"+sigma);
                //trace("term:"+(yi - yFit)/sigma);
                var delYiFitSq:Number = (yi - yFit)*(yi - yFit)
                sum += delYiFitSq/(sigma*sigma);
                modelRef.SSerr += delYiFitSq;
            }//end of for loop
            return sum;
        }//end of computeSum()
             
        this.chiSquare = sum/this.degOfFreedom;
        if(this.nbrPoints <= (orderOfFit +1)){  
            this.chiSquare = 0;
        }
        this.mainView.updateChiScaleDisplay();
    }//end of getReduceChiSquare();
     
    function getChiSquare():Number{
        return this.chiSquare;
    }
```

**Comment by veillette** [comment]
It turns out to be the same approach as used in the flash simulation.
The flash simulation includes a comment about ignoring the error bars for the r square calculation. However the r square result was not as public facing in the flash simulation as it is in the html5 version.

**Comment by veillette** [comment]
After looking into, I found out that
- R-squared is defined as the explained variation / Total variation
- In the case of best-fit line with equal weights, our current approach is correct. It will always yield a r^2 value that lies between 0 and 1.
- For the best fit curve for quadratic and cubic term (with equal weights),  statisticians uses an adjusted value, which takes into account the fact that r^2 increases as one uses more fitting parameters.  Wikipedia talks about it: https://en.wikipedia.org/wiki/Coefficient_of_determination
- It is possible to generalize the calculation of r square for the best fit line with unequal weights. The value of r^2 is guaranteed to fall between 0 and 1. 
-  There is no literature about calculations of r^2 for "man-made" fits. r^2 only applies after the best fit line determined. Currently, r^2 can be negative for man-made fits.

**Comment by veillette** [comment]
A good course of action is to generalize the r square calculation to take into account the weight (Delta value)  associated with each point.

For the user controlled fit, it is still possible to get a negative value for r square. Just as we do now, replace any negative value to zero. 

I note in passing that weighted r square calculation will be used for all setting. However it reduces to our previous result when all the weights are equal. 

The adapted r square is probably too sophisticated for our user base. Using more fitting parameters, students should expect the fit to get better, the chi  square value to go down and the r square value to increase.

**Comment by SaurabhTotey** [comment]
It looks like r^2 squared accounts for weights. Because I don't know what to do with this issue or where to go with it, I am marking this as ready for review.

**Comment by veillette** [comment]
The r^2 calculation takes the weights into account. Closing
