### ISSUE TITLE
Add spacing to values reading

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#8]
![screen shot 2015-04-22 at 9 37 10 am](https://cloud.githubusercontent.com/assets/7852916/7278511/455b9130-e8d3-11e4-8db6-9d5f5cc7b170.png)

There should be spaces before and after "=" as well as after ",". 

![screen shot 2015-04-22 at 9 39 48 am](https://cloud.githubusercontent.com/assets/7852916/7278565/8eedc5c0-e8d3-11e4-8c72-08f6e8a398ab.png)

**Comment by andrey-zelenkov** [comment]
Added spaces to point values reading. Reassign to @amanda-phet for verification.

**Comment by amanda-phet** [comment]
This is fixed. Closing.
