### ISSUE TITLE
quartic polynomials?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#84]
The Java version supports quartic polynomials, the HTML5 version does not.  Since I'm jumping in late in the process, I want to verify that that was a conscious decision, and not a programming oversight.

Java version:

![screenshot_69](https://cloud.githubusercontent.com/assets/3046552/17158268/6dab02f2-5352-11e6-9b39-f2ec30a7fa9b.png)

HTML5 version:

![screenshot_70](https://cloud.githubusercontent.com/assets/3046552/17158275/7a7461f4-5352-11e6-88ba-c48742d7cd23.png)

**Comment by ariel-phet** [comment]
@pixelzoom - this was a conscious decision. Meeting notes in the design doc from October 9 (2015 I believe) have the following

![quartic](https://cloud.githubusercontent.com/assets/4051174/17163878/7d5ab1ba-5380-11e6-86c2-2315df69448a.PNG)

Thanks for checking though! Closing
