### ISSUE TITLE
multiple screens?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#85]
Throughout the [design document](https://docs.google.com/document/d/1_iAkd1nZx5ORLy37przO4wDG2fmHgtn9R5vRFILNUmY/edit#) there is reference to "screen 1" and "screen 2".   They are even mentioned in the October 9 meeting notes - and the last meeting notes are October 23 (no idea what year, but that's a different issue). 

The mockups and implementation, on the other hand, show only 1 screen.

So... Was there an undocumented decision to stick with 1 screen?

**Comment by ariel-phet** [comment]
I believe that "screen 1" became Least Squares Regression.

@amanda-phet - do you recall if that is correct?

**Comment by amanda-phet** [comment]
That's correct- screen 1 eventually became a separate sim. The design section of the sim is the most current and does not reference two different screens.

**Comment by pixelzoom** [comment]
Thanks. Closing.
