### ISSUE TITLE
clean up and restructure

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#87]
This sim is not in great shape, needs a lot of clean up and restructuring.

I did a significant amount of this before realizing that I should have published a "baseline" dev version before starting, since the most recent dev version (1.0.0-dev.4) was published in May 2015.

So I published this dev version (1.0.0-dev.5) as a checkpoint:
http://www.colorado.edu/physics/phet/dev/html/curve-fitting/1.0.0-dev.5/curve-fitting_en.html

**Comment by pixelzoom** [comment]
`BucketAndGraphAreaNode` and `GraphAreaNode` are particularly egregious.

**Comment by pixelzoom** [comment]
I've been reassigned to plinko-probability, so won't be continuing with this sim.  Before I move on, @ariel-phet has asked me to:

- [ ] Clean up anything that I was in the middle of doing
- [ ] Create an issue describing any recommended changes to make the sim more maintainable

**Comment by pixelzoom** [comment]
@ariel-phet I completed the tasks that you requested, see above issues. 

Closing.

**Comment by ariel-phet** [comment]
Excellent, thanks
