### ISSUE TITLE
graphModelBounds not used consistently

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#88]
The model (CurveFittingModel) contains a field for the bounds of the graph:

``` js
42     this.graphModelBounds = CurveFittingConstants.GRAPH_MODEL_BOUNDS;
```

Elsewhere in the code, that field is sometimes used, and sometime clients just use `CurveFittingConstants.GRAPH_MODEL_BOUNDS` directly.   So we should either (a) get rid of this field and use the constant everywhere, or (b) add a property Graph model element and use it everywhere.

**Comment by SaurabhTotey** [comment]
I don't think that this is an issue anymore. Marking as ready for review.
