### ISSUE TITLE
Deviations panel text is not aligned correctly

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#9]
The "Deviations" text should follow the same alignment rules as the "Equation" text. It needs to be vertically centered with the [+] and should be farther from the [+]. 

![screen shot 2015-04-22 at 9 29 03 am](https://cloud.githubusercontent.com/assets/7852916/7278635/e80aa3c6-e8d3-11e4-9022-4881969b8999.png)

**Comment by andrey-zelenkov** [comment]
Added alignment for deviations panel text. Reassign to @amanda-phet for verification.

**Comment by amanda-phet** [comment]
Looks much better now. Closing.
