### ISSUE TITLE
questions about tick marks on the graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#92]
A couple of things I noticed about the tick marks on the graph:

(1) x tick marks are at +5 and -5.  But y tick marks are at +5.7 and -4.3.  Is this a bug, or what was desired? (Looks like a bug introduced between 1.0.0-dev.4 and 1.0.0-dev.5, but figured I'd ask.)

(2) The tick marks are not labeled. Should they be?

**Comment by pixelzoom** [comment]
Looking back through past dev versions and commits, it looks to me like the y-axis tick marks are currently in the incorrect position, and that +5 and -5 is what's desired.  Tracking that issue in https://github.com/phetsims/curve-fitting/issues/93.  But @amanda-phet please verify that it's a bug.

As for the tick labels... My instinct is to change the range of the x and y axes to [-11,11], then label the ticks at -10, -5, 5, 10 on both axes. Having tick marks sitting right on the boundary of the graph is almost alway a bad idea.

**Comment by amanda-phet** [comment]
The tic marks should be at -10, -5, 5 and 10 for both axes. So yes, that's a bug if they are creeping away from that! 

Changing the range of the axes to [-11,11] is fine with me, with tic marks at -10, -5, 5 and 10.

**Comment by pixelzoom** [comment]
Thanks @amanda-phet. Addressing these changes in #93 and #94.  

Closing.
