### ISSUE TITLE
add tick mark labels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#94]
See https://github.com/phetsims/curve-fitting/issues/92.

I said:

> As for the tick labels... My instinct is to change the range of the x and y axes to [-11,11], then label the ticks at -10, -5, 5, 10 on both axes. Having tick marks sitting right on the boundary of the graph (like we have now) is almost alway a bad idea.

@amanda-phet replied:

> Changing the range of the axes to [-11,11] is fine with me, with tic marks at -10, -5, 5 and 10.

**Comment by veillette** [comment]
The previous commit will make it easier to change the position and number of tick lines.

**Comment by SaurabhTotey** [comment]
I believe this issue can be closed. Here is what master looks like right now.

<img width="1390" alt="Screen Shot 2019-06-03 at 2 17 26 PM" src="https://user-images.githubusercontent.com/22577113/58831731-917a0a00-860a-11e9-9351-ebbef0fb53f7.png">

There are tick labels at -10, -5, 5, and 10 for both axes, and the graph bounds are -11 to 11 for both axes.

**Comment by SaurabhTotey** [comment]
Previously, the ticks were close to the axes, but I have since added padding. Assigning to @amanda-phet to review.

**Comment by amanda-phet** [comment]
Looks great to me.
