### ISSUE TITLE
quadratic and cubic incorrectly labeled

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/curve-fitting#95]
Between dev4.5 and dev5 the quadratic and cubic labels got switched. 

You can see in this screenshot (dev.5) that the quadratic equation is incorrectly labeled as cubic. 

![screen shot 2016-08-08 at 12 15 48 pm](https://cloud.githubusercontent.com/assets/7852916/17490795/debfd08a-5d61-11e6-9467-05e6c60e8635.png)

**Comment by pixelzoom** [comment]
Thanks @amanda-phet, labels on the buttons have been fixed.

Closing.

**Comment by pixelzoom** [comment]
![screenshot_77](https://cloud.githubusercontent.com/assets/3046552/17491089/460c95ec-5d63-11e6-8cc9-667577f4d084.png)
