### ISSUE TITLE
make control panels the same width

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/curve-fitting#98]
This was broken during restructuring and cleanup in https://github.com/phetsims/curve-fitting/issues/87.  I was pulled off of curve-fitting before addressing it.

**Comment by pixelzoom** [comment]
This concerns the panels created in type ControlPanel, which currently looks like this:

![screenshot_13](https://cloud.githubusercontent.com/assets/3046552/18214752/9d85b612-710b-11e6-9ff2-e4d2c98b91e6.png)

**Comment by memo330179** [comment]
I took care of this by making the PANEL_MAX_WIDTH and PANEL_MIN_WIDTH the same size. This allows the panels to all take the same size and always be the same relative size no matter the size of the sim.

**Comment by pixelzoom** [comment]
Assigning to myself to review.

**Comment by pixelzoom** [comment]
@memo330179 Is this ready for me to review, or is there additional work to be done?

**Comment by memo330179** [comment]
I think this one is ready for review.

**Comment by pixelzoom** [comment]
Looks good and passes stringTest. Closing.
